"""
Conversational training lines for ElevenLabs TTS generation.
~1000 lines covering diverse topics, emotions, and speech patterns.
Target: ~90K characters ≈ ~80 minutes of audio.
"""

TRAINING_LINES = [
    # ── Greetings & openers ────────────────────────────────
    "Hey! How's it going? I haven't seen you in forever.",
    "Oh my gosh, hi! Come in, come in. Make yourself at home.",
    "Good morning! Did you sleep okay? You look a little tired.",
    "Hey there, welcome back! So glad you could make it.",
    "Oh hey! I was just thinking about you, actually.",
    "Hi! Okay, you look amazing today. What's the occasion?",
    "Well look who it is! It's been ages. How have you been?",
    "Hey you! I was hoping I'd run into you today.",
    "Oh hi! Sorry, I'm a mess right now. Come in anyway.",
    "Good to see you! Grab a seat, I'll be right with you.",

    # ── Casual conversation ────────────────────────────────
    "So I was at the grocery store earlier, right? And this guy just walks up to me and starts telling me about his cat. Like, completely out of nowhere.",
    "I don't know, I've been feeling kind of weird lately. Not bad, just... different, you know?",
    "Wait, you actually did that? That's hilarious. I can't believe you got away with it.",
    "Honestly? I think the best part of my day was just sitting on the porch with my coffee this morning. Sometimes the simple things are everything.",
    "You know what I realized the other day? I've been doing this for almost five years now. Five years! That's crazy when you think about it.",
    "Oh no, don't even get me started on that. I have so many opinions and none of them are good.",
    "That reminds me of something my mom always used to say. She'd be like, just take it one step at a time, honey.",
    "I mean, yeah, it's not perfect, but nothing ever is, right? You just do your best and hope it works out.",
    "Can I be honest with you? I was really nervous about this, but now that we're talking, I feel so much better.",
    "No way. No way! Are you serious right now? Tell me everything.",
    "I tried that new restaurant on Fifth Street yesterday. The pasta was incredible, but the service was kind of slow.",
    "My neighbor got a new puppy and now I can't stop going over there to play with it. It's a golden retriever and it's so fluffy.",
    "I was on the phone with my sister for like two hours last night. We haven't talked that long in months.",
    "Did you know there's a farmers market every Saturday? I went for the first time last week and now I'm obsessed.",
    "I accidentally sent that text to the wrong person and I'm still recovering from the embarrassment.",
    "So apparently, I've been saying that word wrong my entire life. Someone corrected me yesterday and I just stood there in shock.",
    "I've been binge watching this show and I'm only on season two but I already know it's going to ruin me.",
    "My coworker brought homemade cookies today and they were actually incredible. I had like four of them.",
    "I tried to fix the sink myself and ended up making it way worse. Now there's water everywhere.",
    "I found this really cool bookstore downtown that I'd never noticed before. It's tiny but they have the best selection.",

    # ── Questions & curiosity ──────────────────────────────
    "So what have you been up to? Anything exciting going on?",
    "Wait, can you explain that to me? I feel like I'm missing something.",
    "Have you ever tried doing it the other way around? Like, what if you started from the end?",
    "Hmm, that's interesting. What made you decide to go that route?",
    "Do you think it's worth it? Like, genuinely, do you think it's going to make a difference?",
    "What would you do if you were in my shoes? I'm honestly stuck.",
    "Have you eaten yet? I was thinking about ordering something. Maybe Thai food?",
    "So where are you heading after this? Do you have plans for the rest of the day?",
    "Did you see that thing online? The one everyone's been talking about?",
    "What's your take on it? I've heard like five different opinions and I don't know what to think.",
    "Can I ask you something kind of random? Like, it might sound weird but I'm genuinely curious.",
    "What's the best advice anyone's ever given you? I love hearing stuff like that.",
    "How long did it take you to learn that? Because I've been trying and I'm struggling.",
    "You've been there before, right? Is it as good as everyone says?",
    "Okay, honest question. If you had to pick one, which would you choose?",
    "What's your favorite thing about this time of year? I feel like everyone has a different answer.",
    "How did you even find out about that? I feel so out of the loop sometimes.",
    "Do you ever wonder what life would be like if you'd made different choices? Not in a sad way, just curious.",
    "What are you reading right now? I need a new book recommendation so badly.",
    "Have you noticed that too? I thought I was the only one who picked up on it.",

    # ── Reactions & emotions ───────────────────────────────
    "Oh wow, that's amazing! I'm so happy for you, seriously.",
    "Aw, I'm sorry to hear that. That sounds really tough. Are you doing okay?",
    "Ha! That's so funny. You always know how to make me laugh.",
    "Hmm, I'm not sure how I feel about that. Let me think about it for a second.",
    "Oh no, that's not good. What happened? Is everyone alright?",
    "Yay! Finally! I've been waiting for this for so long, you have no idea.",
    "Okay, that's actually kind of adorable. I can't even be mad about it.",
    "Ugh, that's so frustrating. I totally get why you're upset.",
    "Whoa, really? I did not see that coming. That's wild.",
    "Aww, that's the sweetest thing I've heard all day.",
    "Get out! You're kidding me. That's the funniest thing I've ever heard.",
    "Oh, that makes me so sad. I wish there was something I could do.",
    "I'm literally so excited right now. Like, I can't even contain it.",
    "That's actually really impressive. You should be proud of yourself.",
    "Wait, that happened today? Oh my god. How are you so calm about this?",
    "I don't even know what to say. I'm speechless. In a good way though.",
    "That's so annoying. I would have lost my mind if that happened to me.",
    "Okay I'm not gonna lie, that made me tear up a little bit.",
    "Shut up! No! That's incredible. When did this happen?",
    "I'm so relieved. You have no idea how stressed I was about this.",

    # ── Storytelling ───────────────────────────────────────
    "Okay, so picture this. It's like two in the morning, I'm in my pajamas, and there's a raccoon on my porch just staring at me.",
    "Let me tell you about this dream I had last night. It was so weird but also kind of amazing?",
    "So basically what happened was, I showed up thinking it was a casual thing, and it turned out to be this whole big event.",
    "The funniest part is, nobody noticed. Like, I was standing there the whole time and not a single person said anything.",
    "I remember the first time I tried it. I was terrible. Like, embarrassingly bad. But you know what? I kept going anyway.",
    "There was this one time, I think it was last summer, where everything just kind of fell into place perfectly.",
    "So my friend calls me, right? And she's like, you're not gonna believe what just happened. And honestly? I didn't.",
    "The whole thing took about three hours, but it felt like ten minutes. Time just flew by.",
    "I walked in and immediately knew something was different. I couldn't put my finger on it at first, but then I saw it.",
    "It started out as a total disaster, but somehow we managed to turn it around by the end of the night.",
    "So there I was, standing in the rain with no umbrella, and this stranger just hands me theirs and walks away. Just like that.",
    "I spent the entire weekend working on this project and honestly? I've never been more proud of anything in my life.",
    "My dog did the funniest thing yesterday. She saw her reflection in the window and started barking at it for like ten minutes.",
    "We got lost on the way there, which was stressful at the time, but looking back it was actually the best part of the trip.",
    "I was in line at the coffee shop and the person in front of me paid for my drink. It completely made my day.",
    "So we're sitting there having dinner, totally normal, and then the lights just go out. Complete darkness. Everyone screams.",
    "I accidentally wore two different shoes to work today and didn't notice until lunch. Nobody said anything either, which is concerning.",
    "The sunset last night was unreal. I stood there for twenty minutes just watching the sky change colors.",
    "I tried to parallel park in front of a restaurant and it took me seven tries. Everyone on the patio was watching. It was mortifying.",
    "My grandma called me last night and we talked for an hour about nothing and everything at the same time.",

    # ── Advice & support ───────────────────────────────────
    "You know, I think you're being way too hard on yourself. You're doing better than you think.",
    "If it helps, I've been through something similar. It gets easier, I promise.",
    "My advice? Just go for it. The worst thing that can happen is you learn something new.",
    "Take your time, there's no rush. You'll figure it out when you're ready.",
    "I believe in you. I know that sounds cheesy, but I really do.",
    "Sometimes you just need to step back and take a breath. Everything feels more manageable after that.",
    "Here's what I'd do if I were you. I'd start small and build from there.",
    "Don't worry about what everyone else thinks. This is your decision and yours alone.",
    "You've got this. I've seen you handle way harder things than this.",
    "Hey, it's okay to not have all the answers right now. Nobody does.",
    "You don't have to figure everything out today. Just focus on the next step.",
    "Listen, mistakes are how we learn. Don't beat yourself up over it.",
    "I think you already know the answer, you just need someone to tell you it's okay to go with your gut.",
    "The fact that you're even thinking about this shows how much you care. That counts for something.",
    "Give yourself some grace. You're dealing with a lot right now and you're still showing up. That's huge.",
    "You know what helped me when I was going through something similar? I just started writing things down.",
    "I know it feels impossible right now, but trust me, a year from now you'll look back and be amazed at how far you've come.",
    "It's okay to ask for help. That's not weakness, that's wisdom.",
    "Focus on what you can control and let go of the rest. It sounds simple but it really does work.",
    "Hey, you're allowed to change your mind. That's not quitting, that's growing.",

    # ── Opinions & thoughts ────────────────────────────────
    "Personally, I think that's the best option. But hey, what do I know?",
    "I've been thinking about this a lot, and I keep coming back to the same conclusion.",
    "See, I disagree. I think there's more to it than that.",
    "That's a really good point, actually. I hadn't thought about it that way.",
    "I'm kind of torn on this one. There are good arguments on both sides.",
    "If you ask me, the whole thing is overblown. But that's just my opinion.",
    "You know what? You might be right. I'm willing to change my mind on this.",
    "The way I see it, we have two options. And honestly, neither one is perfect.",
    "I used to think the same thing, but then I had this experience that completely changed my perspective.",
    "Okay but hear me out. What if we looked at it from a completely different angle?",
    "I think people overthink this stuff. Sometimes the obvious answer is the right one.",
    "Here's my hot take and feel free to disagree. I think we're all making this way harder than it needs to be.",
    "I go back and forth on this constantly. Today I'm leaning one way, tomorrow who knows.",
    "The more I learn about it, the less sure I am about anything. And honestly, that's kind of exciting.",
    "I think the answer depends on who you ask and what they've been through. There's no one size fits all.",
    "Controversial opinion, but I actually like it. I know most people don't, but I genuinely think it's great.",
    "I've changed my stance on this probably five times this week. It's complicated.",
    "My gut says one thing but my brain says another. Story of my life honestly.",
    "I respect that perspective even though I don't agree with it. That's what makes conversations interesting.",
    "Sometimes I wonder if we're even asking the right questions, you know?",

    # ── Daily life ─────────────────────────────────────────
    "I need to go to the store later. Do you need anything while I'm out?",
    "I'm so tired today. I stayed up way too late watching that show. Do you watch it?",
    "The weather is so nice today! We should do something outside.",
    "I've been meaning to clean out my closet for like three months now. It's getting ridiculous.",
    "Oh, did I tell you? I started learning how to cook. Like, actually cook. It's been an adventure.",
    "My phone's been acting up all day. It keeps freezing at the worst possible moments.",
    "I made this really good recipe last night. I'll send it to you, you'd love it.",
    "Traffic was insane this morning. I sat in my car for like forty minutes just staring at brake lights.",
    "I really need a vacation. Even just a long weekend would be amazing right now.",
    "I just finished that book you recommended. You were right, the ending was incredible.",
    "I reorganized my entire kitchen this weekend and now I can't find anything. But it looks pretty.",
    "I woke up at five thirty this morning and couldn't fall back asleep, so I watched the sunrise. Worth it.",
    "My coffee maker broke and I'm honestly devastated. I've been going to the cafe down the street every morning.",
    "I found a twenty dollar bill in my jacket pocket today. Past me was looking out for future me.",
    "I'm trying to drink more water but I keep forgetting. I set a reminder on my phone and everything.",
    "I've been walking to work instead of driving and it's actually been really nice. Takes longer but I enjoy it.",
    "The power went out last night for like two hours. I just sat there in the dark eating cereal.",
    "I signed up for a yoga class and I'm either going to love it or pull a muscle. No in between.",
    "My apartment smells amazing right now because I'm making soup. Want some?",
    "I need new shoes but shoe shopping is my least favorite activity in the entire world.",

    # ── Empathy & connection ───────────────────────────────
    "I totally understand where you're coming from. That makes a lot of sense.",
    "That must have been so hard for you. I'm really glad you told me about it.",
    "I feel the same way, honestly. It's nice to know I'm not the only one.",
    "You're not alone in this, okay? Whatever you need, I'm here.",
    "I appreciate you sharing that with me. It means a lot that you trust me.",
    "I get it. I really do. And there's nothing wrong with feeling that way.",
    "That sounds like it was a really special moment. Thanks for telling me about it.",
    "I'm proud of you, you know that? You've come such a long way.",
    "It's okay to feel overwhelmed sometimes. We all do.",
    "I'm so glad we're talking about this. I've been wanting to bring it up but didn't know how.",
    "You can always come to me with stuff like this. Seriously, anytime.",
    "I hear you. And I want you to know that your feelings are completely valid.",
    "That took a lot of courage to say. I admire that about you.",
    "We don't have to talk about it if you're not ready. I'll be here when you are.",
    "I've been thinking about what you said and I just want you to know it really stuck with me.",
    "You handled that way better than I would have. Genuinely impressed.",
    "I know this isn't easy, but you're not going through it alone. Remember that.",
    "Thank you for being so open with me. It makes me feel like I can be open too.",
    "I just want to check in. How are you really doing? Not the polite answer, the real one.",
    "It's okay to not be okay. You don't have to pretend everything is fine around me.",

    # ── Playful & fun ──────────────────────────────────────
    "Okay, random question. If you could have dinner with anyone, dead or alive, who would it be?",
    "You're ridiculous, you know that? In the best way possible.",
    "I dare you. No, seriously, I dare you. You won't do it.",
    "That's it, we're doing this. No more excuses. Let's go!",
    "Oh please, you could totally pull that off. Don't even pretend you can't.",
    "Wanna hear something funny? Promise you won't judge me though.",
    "You know what we should do? We should plan a trip. Like, a real one.",
    "I just had the best idea. Okay, it might be a terrible idea, but just listen.",
    "If I had a dollar for every time that happened, I'd be rich by now. Like, actually rich.",
    "You're making that face again. The one where I know you're about to say something sarcastic.",
    "Okay but what if, and hear me out, what if we just didn't? What if we just stayed in and did nothing?",
    "Quick, say the first word that comes to mind. No, faster than that! You took too long.",
    "I bet I can guess what you're thinking right now. No? Okay fine, tell me.",
    "We should have a movie marathon this weekend. I'm talking snacks, blankets, the whole thing.",
    "Okay, new game. You have to describe your day using only song titles. Go.",
    "Stop, stop, I can't laugh anymore. My stomach hurts. Okay tell me one more.",
    "You know what would be hilarious? If we showed up wearing the same thing. Let's plan it.",
    "I'm going to ask you a series of very important questions and I need you to answer honestly.",
    "We need to make a pact right now. We're doing this before the end of the year. Deal?",
    "Your impression of that was spot on. Do it again. Please. One more time.",

    # ── Transitions & natural speech ───────────────────────
    "Anyway, so yeah, that's basically what happened.",
    "But um, getting back to what I was saying earlier.",
    "Oh! That reminds me. I completely forgot to tell you something.",
    "So, yeah. That's kind of where things stand right now.",
    "Hmm, let me think about how to explain this.",
    "Right, right. Okay so the thing is...",
    "Wait, hold on. I lost my train of thought. Oh! Okay, yeah.",
    "I mean, look, at the end of the day, it is what it is.",
    "But anyway, enough about me. What about you? What's new?",
    "So, long story short, everything worked out in the end.",
    "Where was I? Oh right, so then what happened was...",
    "Sorry, I'm rambling. The point I'm trying to make is...",
    "Okay wait, I need to back up. Let me start from the beginning.",
    "Does that make sense? I feel like I'm explaining it badly.",
    "Actually, you know what? Forget what I just said. Here's the real version.",

    # ── Longer expressive passages ─────────────────────────
    "You know what really gets me? It's when people act like everything has to be perfect all the time. Like, no! Life is messy and complicated and that's what makes it beautiful. At least, that's what I think.",
    "I was walking through the park yesterday and I saw this little kid feeding the ducks, and it just made me so happy. Like, that pure joy on their face? We need more of that in the world.",
    "Here's the thing that nobody tells you about growing up. It's not that things get harder, exactly. They just get more nuanced. There's more gray area, you know? Less black and white.",
    "I've been trying this new thing where I write down three things I'm grateful for every morning. And honestly? It sounds kind of silly, but it's actually been making a huge difference.",
    "Sometimes I think about all the random choices that led me to where I am right now. Like, what if I had gone to a different school? Or taken that other job? It's wild to think about.",
    "The best conversations are the ones where you lose track of time. Where you look up and suddenly it's been three hours and you're like, wait, what? How did that happen?",
    "I think the most important thing in any relationship, whether it's friendship or whatever, is just being honest. Even when it's uncomfortable. Especially when it's uncomfortable.",
    "My grandmother used to say that worrying is like paying interest on a debt you might not even owe. I think about that a lot, actually.",
    "There's something really special about early mornings, before anyone else is awake. It's like the whole world is just quiet. And it's all yours for a little while.",
    "I don't know why, but rainy days always make me feel creative. Like, give me a blanket, some tea, and a rainy window, and I could probably write a novel.",
    "The thing about learning something new is that there's always this awkward phase where you're terrible at it. And most people quit during that phase. But if you push through it, that's where the magic happens.",
    "I was thinking about this the other day, about how we all have these little rituals that nobody knows about. Like, I always stir my coffee exactly seven times. Why? No idea. But I do it every single time.",
    "I love those moments where you're with someone and you both just start laughing and you can't stop. And you don't even remember what was funny anymore but you're just crying laughing.",
    "You know what I find fascinating? How different everyone's morning routine is. Like some people are up at five doing yoga and I'm hitting snooze four times and stumbling to the kitchen for coffee.",
    "I read somewhere that the average person makes like thirty five thousand decisions a day. Thirty five thousand! No wonder we're all exhausted by dinner time.",
    "Something I've learned is that the people who seem like they have it all together are usually just really good at hiding the mess. Nobody actually has it figured out.",
    "The older I get, the more I realize how important it is to just be kind. Not impressive, not perfect, just kind. Everything else kind of falls into place after that.",
    "I have this theory that the best ideas come when you're not trying to think of them. Like in the shower, or right before you fall asleep. Your brain does its best work when you stop forcing it.",
    "One of my favorite things in the world is when you're having a conversation with someone and they say something that makes you go, huh, I never thought of it that way. Those moments change you.",
    "I think there's a difference between being alone and being lonely. Sometimes being alone is exactly what you need. It's like recharging your battery.",

    # ── Food & cooking ─────────────────────────────────────
    "Oh my god, this is so good. What did you put in this? You have to give me the recipe.",
    "I tried making bread from scratch for the first time and it was a complete disaster. But I'm gonna try again.",
    "I'm obsessed with this new coffee place. Their lavender latte is life changing, I'm not even exaggerating.",
    "Should we order pizza or sushi? Actually, let's get both. I can't decide and I don't want to.",
    "I've been on a smoothie kick lately. Like, every morning I throw a bunch of fruit in the blender and hope for the best.",
    "The secret ingredient is butter. It's always butter. Every chef will tell you the same thing.",
    "I burned the cookies again. I set a timer and everything but somehow they still came out like little hockey pucks.",
    "You know what's underrated? A really good sandwich. Not fancy, just like, perfect bread, good cheese, fresh veggies.",
    "I went to this little hole in the wall restaurant and had the best meal of my entire life. I'm not exaggerating.",
    "Do you want me to make tea? I just got this new one that smells amazing. It's like chamomile and honey.",

    # ── Travel & adventure ─────────────────────────────────
    "I've always wanted to go to Japan. Like, it's been on my list for years. Maybe next year.",
    "The best trip I ever took was completely unplanned. We just got in the car and drove.",
    "I'm not a great flyer, to be honest. I always grab the armrest during takeoff. Every single time.",
    "There's this little town we stopped at on the way back and it was the cutest place I've ever seen.",
    "I want to go somewhere where nobody knows me and I can just wander around with no agenda. That sounds perfect.",
    "We stayed at this tiny bed and breakfast in the mountains and the view from our window was absolutely breathtaking.",
    "I packed way too much. I always pack too much. I brought four jackets for a three day trip. Why am I like this?",
    "Getting lost in a new city is honestly one of my favorite things. You find the best stuff that way.",
    "The flight got delayed three times and by the end we were all basically best friends in the terminal.",
    "I took the train instead of flying and it was so much more relaxing. I just watched the world go by for six hours.",

    # ── Work & productivity ────────────────────────────────
    "I had the most productive day today and I feel like a completely different person. It's amazing what checking things off a list does for you.",
    "My meeting ran forty five minutes over and I could feel my soul leaving my body by the end.",
    "I think I work best with a little bit of pressure. Not a lot, just enough to keep me focused.",
    "I made a to do list this morning with twelve things on it and I finished exactly two. But you know what? Those two things were important.",
    "Someone brought donuts to the office today and honestly that's all the motivation I needed.",
    "I've been staring at this email for twenty minutes trying to figure out how to word it. Why is professional communication so hard?",
    "I love working from home but some days I really miss having people around. The quiet gets to you after a while.",
    "I had this great idea in the shower this morning and by the time I got to my desk I completely forgot it.",
    "My desk is a disaster right now but I know where everything is. It's organized chaos. Don't touch anything.",
    "I finished that project early and I don't even know who I am anymore. This never happens.",

    # ── Seasons & weather ──────────────────────────────────
    "I love fall so much. The colors, the sweaters, the hot chocolate. Everything about it is perfect.",
    "It's raining again and I'm not even mad. There's something so cozy about a rainy day when you're inside.",
    "Spring is when I come alive. The second I see the first flowers I just feel this burst of energy.",
    "It's so cold outside that my face hurt on the walk over. I could barely feel my nose by the time I got here.",
    "Summer evenings are my favorite. You know those nights where it's warm and the sky turns that golden color?",
    "I'm ready for winter to be over. I love it in December but by February I'm just done.",
    "The snow is beautiful when it first falls, all clean and white. And then it turns into gray slush and I want to move somewhere tropical.",
    "Today is one of those perfect weather days. Not too hot, not too cold, just right. I wish I could bottle this feeling.",
    "I sat outside and read for three hours today. The sun was warm on my face and there was a nice breeze. That's living.",
    "The thunderstorm last night was intense. I love watching lightning from inside though. There's something thrilling about it.",

    # ── Memories & nostalgia ───────────────────────────────
    "I found this old photo of us from like ten years ago and we look so different. But also somehow exactly the same?",
    "That song just came on and it took me right back to high school. Isn't it wild how music does that?",
    "I drove past my old house the other day. It looks completely different now but the tree in the front yard is still there.",
    "Remember when we used to think staying up until midnight was rebellious? Now I can barely make it to ten.",
    "I was going through old messages and found this whole conversation we had that I completely forgot about. It made me smile.",
    "Childhood summers felt like they lasted forever, didn't they? Like each day was a lifetime.",
    "I miss the days when our biggest worry was what game to play at recess. Things were so simple.",
    "My mom sent me a box of old stuff from my room and it was like opening a time capsule. I found journals from when I was thirteen.",
    "There's this smell, I can't even describe it, but whenever I smell it I'm immediately back at my grandparents' house.",
    "I think about that trip we took every time I hear a certain song. Some memories are just permanently linked to things.",

    # ── Hobbies & interests ────────────────────────────────
    "I just started learning guitar and my fingers are killing me. But I can play like three chords now, so that's progress.",
    "I've been really into gardening lately. There's something so satisfying about watching something you planted actually grow.",
    "I painted something yesterday and it's terrible but I don't care. The process was fun and that's what matters.",
    "I've been running every morning and I actually kind of love it now? I never thought I'd say that.",
    "I'm teaching myself to knit and so far I've made a very lopsided scarf. But hey, it's warm.",
    "Photography has become my new obsession. I keep stopping to take pictures of everything and my friends are getting annoyed.",
    "I joined a book club and it's the best decision I've made this year. We meet every two weeks and it's so fun.",
    "I've been doing crossword puzzles before bed and it's weirdly relaxing. Way better than scrolling on my phone.",
    "I'm trying to learn a new language and some days I feel like a genius and other days I can't remember the word for hello.",
    "I started journaling again after years of not doing it and I forgot how therapeutic it is.",

    # ── Friendship ─────────────────────────────────────────
    "You're one of those people I can not talk to for months and then we pick up right where we left off. I love that about us.",
    "I don't say this enough, but you're a really good friend. Like, genuinely one of the best people I know.",
    "We need to do this more often. I always forget how much better I feel after we hang out.",
    "I'm so grateful for you. Not in a cheesy way, just in a real, honest way.",
    "You always know exactly what to say. How do you do that? Is it a superpower?",
    "I was telling someone about you the other day and I realized how lucky I am to have you in my life.",
    "Promise me we'll still be doing this when we're old. Like, sitting on a porch somewhere, still having these conversations.",
    "You're the person I text first when something good happens and also when something bad happens. That says a lot.",
    "I don't need a lot of friends. I just need the right ones. And you're definitely one of the right ones.",
    "Thank you for always being honest with me, even when it's not what I want to hear. That matters more than you know.",

    # ── Self reflection ────────────────────────────────────
    "I've been doing a lot of thinking lately about who I want to be versus who I am. There's still a gap, but it's getting smaller.",
    "I realized I spend so much time worrying about the future that I forget to enjoy what's happening right now.",
    "I'm trying to be more present. Like, actually here, in this moment, instead of always being in my head.",
    "I think I'm finally getting comfortable with not knowing all the answers. That used to terrify me.",
    "I've been working on setting boundaries and it's hard but so worth it. I feel like a completely different person.",
    "Some days I feel like I have everything figured out and other days I feel like I know absolutely nothing. There's no in between.",
    "I've learned that it's okay to outgrow things. People, places, habits. It doesn't mean they were bad, just that you've changed.",
    "I used to think being busy meant I was being productive. Turns out those are very different things.",
    "The hardest lesson I've had to learn is that not everything deserves a reaction. Sometimes silence is the most powerful response.",
    "I'm trying to stop comparing myself to other people. Everyone's on their own timeline and that's perfectly fine.",

    # ── Technology & modern life ───────────────────────────
    "My phone died in the middle of something important and I had to just sit there and exist. It was honestly kind of nice.",
    "I spent an hour trying to figure out why my wifi wasn't working and it turns out the router was just unplugged.",
    "Social media is so weird. Like, I know it's not real but it still makes me feel some type of way sometimes.",
    "I deleted all my apps for a weekend and I don't think I've ever been more at peace in my life.",
    "Remember when we used to have to print out directions from the computer? How did we ever get anywhere?",
    "I love technology but sometimes I miss when things were simpler. Like, when you had to actually call someone to make plans.",
    "I accidentally liked a photo from three years ago while stalking someone's profile. I think I need to change my name and move.",
    "My password got locked and the security question was what's your favorite movie from twenty twelve. I have no idea.",
    "Group chats are either the best thing ever or an absolute nightmare. There is no middle ground.",
    "I watched a tutorial on how to do this thing and the video was twelve minutes long but the actual useful part was thirty seconds.",

    # ── Nature & outdoors ──────────────────────────────────
    "I went for a hike this morning and the view from the top was absolutely worth every painful step.",
    "There's this spot by the lake where I go when I need to clear my head. It's the most peaceful place I know.",
    "Did you see the moon last night? It was so big and bright. I just stood there staring at it like an idiot.",
    "I heard birds singing this morning and it made me unreasonably happy. I don't know what kind they were but they were loud.",
    "The ocean always puts things in perspective for me. You stand there looking at all that water and suddenly your problems feel smaller.",
    "I picked wildflowers on my walk today. They're sitting in a jar on my table right now and they make me smile every time I look at them.",
    "There's nothing quite like the sound of wind through trees. It's like nature's white noise machine.",
    "I saw a double rainbow yesterday and I literally gasped. It was the most vibrant thing I've ever seen.",
    "I'm convinced that houseplants have personalities. My fern is dramatic, my succulent is low maintenance, and my orchid is a diva.",
    "Fresh air really does fix everything. Or at least it fixes like seventy percent of things. I'll take those odds.",

    # ── Gratitude & positivity ─────────────────────────────
    "You know what? Today was a good day. Not perfect, but good. And I think that's enough.",
    "I'm really grateful for this. For us. For this conversation. It sounds small but it means a lot.",
    "I woke up today feeling hopeful and I'm going to ride that feeling for as long as I can.",
    "The little things really are the big things. A good cup of coffee, a text from a friend, a beautiful sky. That's the good stuff.",
    "I don't need everything to go right. I just need enough things to go right. And today, enough things did.",
    "Thank you for being here. I know it might not seem like a big deal but your presence matters.",
    "I'm choosing to focus on what's going well instead of what's going wrong. It's a work in progress but I'm trying.",
    "Every time I think about giving up, something small happens that reminds me why I'm doing this.",
    "Life is short and weird and beautiful and I'm just trying to enjoy the ride.",
    "I don't know what tomorrow holds but I know I'll figure it out. I always do. We always do.",

    # ── Miscellaneous natural conversation ─────────────────
    "Oh shoot, I think I left my keys inside. Hold on, let me check my bag. Nope. My pocket? Yes! Okay, we're good.",
    "I keep meaning to call you back and then I get distracted and then it's like midnight and I'm like, too late now.",
    "You know that thing where you walk into a room and forget why you went in there? That's been my entire day.",
    "I wrote myself a note and now I can't read my own handwriting. I think it says pick up milk? Or maybe it says something else entirely.",
    "My alarm didn't go off this morning so I woke up in a full panic. Turns out it was Saturday. I panicked for nothing.",
    "I just realized I've been humming the same song for three days straight and I don't even like the song.",
    "Do you ever have one of those days where everything is mildly inconvenient? Not bad, just annoying. That's today.",
    "I ran into someone I know but I couldn't remember their name so I just kept saying hey you. I think they noticed.",
    "I told myself I was going to go to bed early tonight and here I am. It's midnight and I'm wide awake.",
    "I need to start writing things down because my memory is absolutely not what it used to be.",
    "Can you hold this for a second? Actually no, give it back. Actually wait, yeah hold it. Sorry, I'm a mess.",
    "I just sneezed like eight times in a row and now I feel like I ran a marathon.",
    "Why do I always remember the things I need to do right as I'm falling asleep? Every single time.",
    "I waved at someone I thought I knew and it was a complete stranger. We're both pretending it didn't happen.",
    "I've been sitting here trying to think of the word and it's right on the tip of my tongue. What's it called when... oh forget it, it'll come to me later.",

    # ── Relationships & dating ─────────────────────────────
    "He texted me back and I stared at my phone for five minutes before opening it. Why do I do this to myself?",
    "First dates are so weird. You're basically interviewing each other but pretending it's casual. It's exhausting.",
    "She said the sweetest thing to me yesterday and I've been thinking about it nonstop.",
    "I think the key to a good relationship is laughing together. If you can't laugh with someone, what's the point?",
    "My friend is going through a breakup right now and I just want to wrap her in a blanket and feed her ice cream.",
    "I got the biggest butterflies when I saw them. Like, actual stomach flipping. I thought that only happened in movies.",
    "We stayed up talking until three in the morning and it felt like no time had passed at all.",
    "I'm not looking for perfect. I'm looking for someone who makes the imperfect stuff feel okay.",
    "Long distance is hard. Like, really hard. But some people are worth the distance, you know?",
    "He remembered that thing I mentioned weeks ago. The little details. That's what gets me every time.",

    # ── Family ─────────────────────────────────────────────
    "My dad called me today just to tell me he saw a bird he thought I'd like. That man is everything.",
    "My sister and I fought about the dumbest thing yesterday but we were laughing about it by the end of the night.",
    "My mom makes this one dish that nobody else can replicate. I've tried a hundred times. It's never the same.",
    "Family dinners are chaos but they're my favorite kind of chaos.",
    "I look more and more like my mother every year and honestly? I'm not even mad about it anymore.",
    "My little brother called me for advice and it hit me that he's not so little anymore. When did that happen?",
    "My grandparents have been married for fifty two years and they still hold hands. Goals, honestly.",
    "I was looking at old family photos and I can't believe how young my parents looked. They were basically our age.",
    "My aunt sent me a random care package in the mail with snacks and a handwritten note. I cried a little.",
    "Sunday mornings at my parents' house. Pancakes, bad jokes, everyone talking over each other. I miss that so much.",

    # ── Movies, shows & entertainment ──────────────────────
    "I just watched this movie and I need to talk about it immediately or I'm going to explode.",
    "No spoilers! I haven't finished it yet. Don't even hint at anything. I'm serious.",
    "That plot twist at the end? I literally gasped. Out loud. In public. People stared.",
    "I've rewatched that show like four times and I notice something new every single time.",
    "The soundtrack in that movie was incredible. I've been listening to it on repeat all week.",
    "I can't believe they cancelled that show. It was so good! I'm genuinely upset about it.",
    "We should do a movie night. I'll bring the popcorn, you pick the movie. But not horror. I can't do horror.",
    "I started watching this documentary and now I know way too much about something I didn't care about before.",
    "The acting in that scene was so good it gave me chills. Actual physical chills.",
    "I need a new show to binge. I've watched everything and nothing sounds good anymore. Help.",

    # ── Music ──────────────────────────────────────────────
    "This song came on shuffle and I haven't been able to stop playing it. I think I've listened to it twenty times today.",
    "I went to this concert last weekend and it was a spiritual experience. I'm not exaggerating.",
    "There's something about live music that recordings just can't capture. The energy, the crowd, everything.",
    "I made a playlist for driving and it's honestly the best thing I've ever created. Very curated. Very vibe.",
    "Do you ever hear a song for the first time and just know it's going to be one of your favorites? That happened today.",
    "I can't listen to that song anymore. It reminds me of a specific time in my life and it hits too hard.",
    "My music taste is all over the place. Like, I'll go from jazz to pop punk in the same playlist. No shame.",
    "I've been learning the lyrics to this song in another language and I have no idea if I'm saying it right.",
    "That bass drop gave me goosebumps. Literally. Look at my arm. Full goosebumps.",
    "Nothing hits quite like the perfect song at the perfect moment. It's like the universe is DJ-ing your life.",

    # ── Health & wellness ──────────────────────────────────
    "I've been sleeping so much better since I stopped looking at my phone before bed. Game changer.",
    "I tried meditation and my brain would not stop talking. Like, the whole point is to be quiet and I just couldn't.",
    "I went to the doctor and she said I need to drink more water and stress less. Easier said than done, doc.",
    "I stretched this morning for the first time in months and my body made sounds I didn't know it could make.",
    "I think I'm getting sick. My throat feels scratchy and I'm in denial about it.",
    "I started taking walks after dinner and it's become the best part of my day. Just me and my thoughts and the sunset.",
    "Self care isn't always bubble baths and face masks. Sometimes it's saying no to plans and going to bed at nine.",
    "I've been trying to eat healthier but chips keep finding their way into my grocery cart. They're sneaky like that.",
    "I finally went to the dentist after putting it off for way too long. It wasn't as bad as I built it up to be.",
    "Mental health days should be mandatory. Some days you just need to rest and that should be totally acceptable.",

    # ── Pets & animals ─────────────────────────────────────
    "My cat did this thing where she just stared at the wall for ten minutes. I'm convinced she sees ghosts.",
    "We adopted a dog last month and my entire life now revolves around this animal. Zero regrets.",
    "I was walking and a butterfly landed on my hand and I literally froze. I didn't want to scare it away.",
    "My friend's parrot can say hello and it makes me laugh every single time. Every time.",
    "I saw the cutest puppy at the park today and I asked the owner if I could pet it and then I didn't want to leave.",
    "My fish has more personality than some people I know. He does this little wiggle when he sees me coming.",
    "I'm definitely a dog person but cats are growing on me. They're so independent and sassy. I respect that.",
    "The neighbor's cat visits me every morning and I've started buying treats for it. I think I've been adopted.",
    "I took my dog to the beach for the first time and she lost her mind. Just running in circles, pure joy.",
    "I showed my cat a video of birds on my phone and she tried to catch them through the screen. Adorable and dumb.",

    # ── Learning & education ───────────────────────────────
    "I learned something today that completely blew my mind. Did you know that octopuses have three hearts?",
    "I've been watching lectures online for fun and I think that officially makes me a nerd. I'm okay with it.",
    "The more I learn about history, the more I realize how wild it actually was. They didn't teach us the good stuff in school.",
    "I'm trying to learn Spanish and I can order food and say thank you but that's about it so far.",
    "I asked a really dumb question today and you know what? I'm glad I did because now I actually understand it.",
    "Reading before bed has become my favorite habit. I learn something new every night and then fall asleep feeling smarter.",
    "I watched this Ted Talk that made me completely rethink how I approach problems. I'll send you the link.",
    "I love when someone explains something complicated in a simple way. That's a real skill and not enough people have it.",
    "I've been down a Wikipedia rabbit hole for the last two hours and I regret nothing.",
    "You know what's cool? That we can learn literally anything right now from our phones. That's insane when you think about it.",

    # ── Dreams & aspirations ───────────────────────────────
    "If money wasn't a thing, I'd open a little cafe by the ocean. Good coffee, live music on weekends, cozy vibes.",
    "I've always wanted to write a book. I have so many ideas but actually sitting down and writing is the hard part.",
    "My dream is to travel for a whole year. Just go wherever the wind takes me. No itinerary, no schedule.",
    "I want to build something that matters. I don't know what yet, but I know it's out there waiting for me.",
    "Sometimes I imagine what my life will look like in ten years and I get this mix of excitement and terror.",
    "I want to learn to play piano before I turn thirty. I've said this every year for five years but this time I mean it.",
    "My secret dream is to live in a cabin in the woods with a dog and a garden. Very simple, very peaceful.",
    "I've been thinking about going back to school. It's scary but exciting at the same time.",
    "I want to be the kind of person people feel comfortable around. Like, a safe place. That's my goal.",
    "I keep a list of things I want to do before I die and I crossed one off last week. It felt incredible.",

    # ── Funny observations ─────────────────────────────────
    "Why is it that the shopping cart always picks you? Like, out of a hundred carts, you always get the one with the wobbly wheel.",
    "I put my glasses on to find my glasses the other day. I need a moment.",
    "The audacity of my alarm clock. Every single morning it has the nerve to go off and I take it personally.",
    "I said goodbye to someone and then we walked in the same direction for three blocks. The most awkward walk of my life.",
    "I rehearsed what I was going to say for twenty minutes and then completely blanked when the moment came.",
    "My brain at three AM decides that now is the perfect time to remember that embarrassing thing I did in two thousand and fourteen.",
    "I tried to open a push door by pulling it and made eye contact with someone on the other side. I can never go back there.",
    "I overheard someone arguing about whether a hot dog is a sandwich and honestly both sides made valid points.",
    "I typed an entire message, read it back, deleted it, typed it again differently, and then just didn't send it.",
    "Why does food taste better when someone else makes it? I can make the exact same thing and it's just not the same.",
    "I tripped over absolutely nothing on a flat surface. The ground just decided to betray me today.",
    "I set an alarm to remind me to do something and when it went off I snoozed it. Defeated the whole purpose.",
    "My autocorrect has turned me into a completely different person. The things it thinks I'm trying to say are concerning.",
    "I accidentally called my teacher mom once and I still think about it to this day. Some wounds don't heal.",
    "I held the door for someone who was way too far away and then we both had to do that awkward jog thing.",

    # ── Deeper conversations ───────────────────────────────
    "Do you think people can really change? Like, fundamentally change who they are? I go back and forth on this.",
    "What do you think happens when we die? I'm not trying to be morbid, I'm genuinely curious what you believe.",
    "I think about time a lot. Like, this moment right now will never happen again. That's kind of beautiful and kind of terrifying.",
    "Do you think everything happens for a reason or do we just make meaning out of random events? I honestly don't know.",
    "I wonder sometimes if the version of me that exists in your head is different from who I actually am.",
    "What if the thing you're most afraid of is actually the thing you're supposed to do? I keep coming back to that idea.",
    "I think loneliness is one of those things nobody talks about enough. Like, you can be surrounded by people and still feel alone.",
    "The concept of home is interesting to me. Is it a place or a feeling? Because I think it might be a feeling.",
    "I read somewhere that we're all just walking each other home. I don't know why but that really stuck with me.",
    "Do you think we choose who we become or does life just sort of shape us? Maybe it's both.",
    "I've been thinking about legacy lately. Not in a big, grand way, but just like, what will people remember about me?",
    "There's this idea that we have multiple lives within our one lifetime. Like, every few years you become a new version of yourself.",
    "I wonder if other people's internal monologue sounds anything like mine. Is everyone's brain this chaotic?",
    "Something I find comforting is that the stars we see at night are millions of years old. We're literally looking at the past.",
    "I think vulnerability is the bravest thing a person can be. It takes so much more courage to be open than to be guarded.",

    # ── Complaining & venting ──────────────────────────────
    "I just need to vent for a second. I'm not looking for advice, I just need someone to listen. Is that okay?",
    "Why does everything take longer than it should? I budgeted thirty minutes for this and it's been two hours.",
    "I am so over this week and it's only Tuesday. Tuesday! How is it only Tuesday?",
    "The wifi went out right in the middle of the most important part. Of course it did. Of course.",
    "I've been on hold for forty five minutes. Forty five minutes! I could have driven there by now.",
    "Someone ate my lunch from the fridge. My clearly labeled lunch. With my name on it. I'm livid.",
    "I just want one day where nothing goes wrong. Just one. Is that too much to ask?",
    "The construction outside my window starts at seven AM every single morning. I haven't slept properly in weeks.",
    "I missed my exit on the highway and the next one was like fifteen miles away. Fifteen miles of frustration.",
    "I wrote this whole thing and then my computer crashed and I lost everything. I didn't save. I never save. Why don't I save?",

    # ── Encouragement & motivation ─────────────────────────
    "You're closer than you think. Seriously. Don't give up now.",
    "Every expert was once a beginner. Remember that when you're feeling like you're not good enough.",
    "Today might not be your day. But your day is coming. I can feel it.",
    "You've survived every bad day so far and that's a pretty impressive track record.",
    "Do the thing that scares you. Not the reckless stuff, but the stuff that scares you because it matters.",
    "Progress isn't always visible. Sometimes you're growing in ways you can't see yet. Trust the process.",
    "You don't have to be fearless. You just have to be willing to do it afraid.",
    "The fact that you keep trying says more about you than any failure ever could.",
    "Start messy. Start scared. Start unsure. Just start. You can figure out the rest as you go.",
    "Remind yourself why you started. That reason is still valid and so are you.",

    # ── Cooking conversations ──────────────────────────────
    "Okay so you're gonna want to sauté the onions first until they're translucent. That's the base of everything.",
    "I added way too much salt and I'm trying to figure out if there's any way to save this. Potato trick maybe?",
    "The smell of fresh bread baking is literally the best smell in the entire world. I will die on this hill.",
    "I don't follow recipes exactly. I just use them as a rough guide and then wing it. It usually works out.",
    "My kitchen looks like a disaster zone right now but the food is going to be worth it. I hope.",
    "I learned how to make homemade pasta and I feel like I've unlocked a superpower.",
    "The trick to good scrambled eggs is low heat and patience. Most people cook them way too fast.",
    "I got a new cast iron skillet and I'm treating it better than I treat most humans. Seasoning it, caring for it, the whole thing.",
    "Cooking for other people is my love language. There's something so special about feeding someone you care about.",
    "I tried to flip a pancake by tossing it in the air and it landed on the floor. The dog was thrilled though.",

    # ── Night & morning routines ───────────────────────────
    "I'm such a morning person and I know that annoys people but I can't help it. The sunrise is right there!",
    "Getting out of bed is the hardest part of my day. Once I'm up, I'm fine. It's just that initial separation from the pillow.",
    "I have this whole bedtime routine now. Tea, book, no phone, lights out by ten. It changed my life.",
    "Three AM thoughts are a different breed. Everything feels more intense and more real in the middle of the night.",
    "I love that quiet hour right before everyone wakes up. It feels like the world is mine for a little while.",
    "My morning coffee is non negotiable. Don't talk to me, don't ask me questions, just let me have my coffee.",
    "I've been trying to wake up without an alarm and my body just naturally wakes up at like ten. So that's not working.",
    "The best part of going to bed is getting into freshly washed sheets. It's like a hug from the universe.",
    "I can't sleep when it's too quiet. I need a fan or rain sounds or something. Total silence freaks me out.",
    "I've become the person who goes to bed at nine thirty and I have zero regrets about it.",

    # ── Seasons & holidays ─────────────────────────────────
    "There's nothing like the first warm day after a long winter. Everyone suddenly comes to life.",
    "I love decorating for the holidays. I go way overboard but it makes me happy so who cares?",
    "Fall candles are out at the stores and I bought six. Am I going to burn all of them? Absolutely.",
    "New Year's resolutions are just goals with a fancy deadline. I make the same ones every year.",
    "Summer nights with the windows open and crickets outside. That's the stuff right there.",
    "I went apple picking last weekend and ate way more apples than I picked. No regrets.",
    "The first snowfall of the year is magical. Every snowfall after that is just annoying.",
    "I love how everyone becomes a little nicer around the holidays. Like, that energy should be year round.",
    "Beach days are my therapy. Sand between my toes, waves crashing, sun on my face. That's healing.",
    "I carved a pumpkin last night and it looks absolutely terrible but I'm displaying it proudly anyway.",

    # ── Quirks & confessions ───────────────────────────────
    "I eat cereal at midnight sometimes and it hits different. Like, breakfast food at night is elite.",
    "I talk to my plants. Full conversations. I think it helps them grow but honestly it helps me more.",
    "I always read the last page of a book first. I know that's unhinged but I like knowing where it's going.",
    "I still sleep with a stuffed animal and I'm not ashamed. His name is Captain Fluffington.",
    "I sing in the shower like I'm performing at a sold out concert. Full choreography. Standing ovation.",
    "I cry at commercials. Not sad ones necessarily, just the ones where people are being nice to each other.",
    "I have a very specific way I like my sandwiches cut and I will not apologize for being particular about it.",
    "I name everything. My car, my phone, my laptop. They all have names and personalities.",
    "I keep checking my phone even though nobody texted me. It's a reflex at this point.",
    "I practice arguments in the shower. Like, full debates with people who aren't there. I always win, obviously.",

    # ── Appreciation & closing ─────────────────────────────
    "This has been really nice. I'm glad we did this. We need to do this more often.",
    "Thanks for listening. Seriously. Sometimes you just need someone to hear you.",
    "I should probably get going but I don't want to. Can we just sit here a little longer?",
    "You always make me feel better. I don't know how you do it but don't ever stop.",
    "Alright, I should let you go. But text me later, okay? I want to hear how it goes.",
    "This was exactly what I needed today. Just this. Just talking. Thank you.",
    "I'm so glad I know you. Like, out of all the people in the world, I got you. Pretty lucky.",
    "Take care of yourself, okay? And I mean actually take care of yourself, not just say you will.",
    "Same time next week? I'm already looking forward to it.",
    "Goodnight. Sweet dreams. And if you can't sleep, you know who to call.",

    # ── More extended monologues ───────────────────────────
    "I had this moment last week where I was driving home and the sun was setting and this perfect song came on, and I just felt so alive. Like, everything was exactly as it should be. Those moments don't happen often but when they do, you hold onto them.",
    "I think one of the most underrated skills is knowing how to listen. Not just waiting for your turn to talk, but actually listening. Most people don't do that and you can tell. But when someone really listens to you? It changes everything.",
    "There's this quote I read once that said we don't remember days, we remember moments. And I think that's so true. I can't tell you what I did last Thursday, but I can tell you about that time we laughed so hard we cried at that restaurant.",
    "I used to be so afraid of failing that I wouldn't even try. And then one day I realized that not trying was its own kind of failure. The biggest one, actually. Because at least when you try and fail, you learn something.",
    "You know what makes someone attractive? Not looks, not money. It's when they're genuinely passionate about something. Like, when their eyes light up talking about whatever it is they love. That energy is magnetic.",
    "I've been thinking about how different our lives would be if we said yes more often. Not to everything, but to the things that scare us a little. The things that make us think, what if? I think that's where the good stuff lives.",
    "The world feels really heavy sometimes and I think it's okay to acknowledge that. You don't have to pretend everything is fine all the time. Sometimes things are hard and the bravest thing you can do is say, yeah, this is hard, and keep going anyway.",
    "I believe in signs. Not in a woo woo way, but in a paying attention way. Like, when the same idea keeps showing up in different places, maybe the universe is trying to tell you something. Or maybe it's just your brain noticing patterns. Either way, I listen.",
    "One thing I've learned is that you can't pour from an empty cup. You have to take care of yourself first before you can show up for anyone else. And that's not selfish. That's survival. That's sustainability. That's love, actually.",
    "I think the bravest thing any of us can do is be exactly who we are. Not the version we think people want to see, but the real, messy, imperfect, beautiful version. The one that laughs too loud and cries at movies and says the wrong thing sometimes. That version. That's the one worth being.",

    # ── Additional varied conversation ─────────────────────
    "Did you just say what I think you said? Hold on, repeat that. I need to hear it again.",
    "I keep going back and forth. One minute I'm sure, the next minute I have no idea.",
    "That jacket looks amazing on you, by the way. Where did you get it?",
    "I completely forgot what I was going to say. It was important too. It'll come back to me.",
    "We should start a tradition. Like, every first Friday of the month we do something fun together.",
    "I'm the kind of person who arrives fifteen minutes early to everything. I can't help it. It stresses me out to be late.",
    "Do you ever think about how many strangers you've appeared in the background of someone's photo?",
    "I bought this on impulse and I already know I'm going to regret it. But right now? No regrets.",
    "My handwriting is getting worse every year because I type everything now. I wrote a card recently and it looked like a doctor's note.",
    "I had the weirdest interaction at the bank today. The teller asked me how my day was and I said you too. Classic.",
    "I love a good metaphor. Like, life isn't a highway, it's more like a hiking trail. Sometimes uphill, sometimes flat, occasionally you step in mud.",
    "I'm that person who claps when the plane lands and I refuse to be embarrassed about it. We made it!",
    "Someone complimented my shoes today and I've been riding that high for hours. Literal hours.",
    "I think there's an art to doing nothing. Like, productive nothing. Where you're just existing and it's wonderful.",
    "We ordered the same thing. I love when that happens. It means we're on the same wavelength.",
    "I have a theory that the best friendships are the ones where you can sit in silence and it's not weird.",
    "I just found out we have the same birthday and I feel like that means something. I don't know what, but something.",
    "The thing about getting older is that you care less about what people think. And honestly? It's incredibly freeing.",
    "I'm going to need you to say that one more time because I want to make sure I heard you correctly.",
    "You have this way of making everything sound interesting. Even boring stuff. That's a gift.",
    "I wish I could freeze this moment. Just pause time right here and stay in it for a while.",
    "Is it just me or does everything taste better when you eat it outside? Like, a regular sandwich becomes gourmet.",
    "I've decided that my personal brand is enthusiasm. I'm just going to be really excited about everything from now on.",
    "I lost track of what day it is and honestly that might be the most relaxed I've felt in months.",
    "That was the perfect response. Like, you just said exactly what I needed to hear without even knowing it.",
    "I think we underestimate how powerful a good hug is. Like, a real one. The kind that says I've got you.",
    "I caught myself smiling for no reason today and I thought, huh, maybe things are good. Maybe things are actually really good.",
    "Tell me something I don't know. Anything. A random fact, a secret, a story. I just want to learn something new.",
    "I'm at that point in the day where I could either take a nap or have another coffee. This is the critical decision.",
    "You know those people who just radiate warmth? Like, you feel better just being around them? You're one of those people.",

    # ── Expressive interjections & reactions ────────────────
    "Oh! Oh wow. Okay, I was not expecting that. Like, at all.",
    "Whoa whoa whoa, hold on. Back up. Say that again?",
    "Ugh, come on! Really? That's the third time this week.",
    "Oh my god, yes! That's exactly what I've been trying to say! Thank you!",
    "Hmm. Hmm hmm hmm. See, that's the part that doesn't add up.",
    "Ha! Oh man, that's good. That is really good.",
    "Aww! Oh my heart. That's so precious I can't handle it.",
    "Ooh, interesting. Tell me more. I'm intrigued.",
    "Yikes. Yeah, that's... that's not great. I'm sorry.",
    "Ohhh, I see. I see what you did there. Very clever.",
    "Nah, no way. I don't believe it. Show me proof.",
    "Huh. I never thought about it like that before. Huh.",
    "Oh gosh, that's embarrassing. But also hilarious. I'm sorry for laughing.",
    "Eww, no! Why would you tell me that? Now I can't unknow it!",
    "Wow. Just... wow. I have chills right now. Actual chills.",
    "Oof. That hit different. I felt that one in my chest.",
    "Oh shoot, wait. I think I left the oven on. No, wait. I didn't cook today. We're fine. False alarm.",
    "Woah. Okay. Let me just process this for a second. Give me a moment.",
    "Phew! That was close. Way too close. My heart is still racing.",
    "Oh come on, don't be like that. You know I was kidding.",

    # ── Surprised reactions ────────────────────────────────
    "Wait, what?! Since when?! How did I not know about this?",
    "Oh! Oh no. Oh no no no. Tell me you didn't.",
    "Whaaaat? Get out of here! You're lying. You have to be lying.",
    "Oh my gosh, really? That's amazing! I'm literally so happy right now!",
    "Hold on, hold on, hold on. You're telling me this has been going on for how long?",
    "No! Shut up! Are you serious?! When did this happen?!",
    "Oh wow, okay, that changes everything. Like, completely changes everything.",
    "Wait wait wait. So you're saying... oh. OH. I get it now.",
    "Hmm, that's not what I expected you to say. But okay, I can work with that.",
    "Gasp! No way. You did not just say that to me. I'm shook.",

    # ── Emotional & expressive longer lines ────────────────
    "Oh man, I haven't laughed that hard in so long. Like, my stomach hurts and my eyes are watering and I can barely breathe. That was so funny.",
    "Ugh, this day has been so long. Like, it started out okay but then everything just went sideways and now I'm just... done. I'm so done.",
    "Aww, you remembered! Oh my gosh, that's so sweet. You didn't have to do that but the fact that you did means everything to me.",
    "Whoa, okay, that's a lot to take in. Let me just sit with that for a second because my brain is doing somersaults right now.",
    "Oh no, babe, don't cry. Hey, it's okay. It's going to be okay. Come here. Let's figure this out together.",
    "Ha! Oh, the irony. The sweet, beautiful irony. You can't make this stuff up. Life is absolutely wild sometimes.",
    "Mmm, this is so good. Oh my god. What is in this? No seriously, what did you put in this because it's incredible.",
    "Ugh, I'm so frustrated with myself. I know what I should do, I just can't get myself to do it. It's like my brain and my body are having a disagreement.",
    "Oh! I just remembered something. So the other day, and this is going to sound crazy, but just bear with me on this one.",
    "Wow, that was really brave of you. Like, genuinely. I don't know if I could have done that. I'm really impressed.",

    # ── Thinking out loud ──────────────────────────────────
    "So... hmm... okay so what if we tried doing it the other way? Like, instead of starting from scratch, what if we just tweaked what we already have?",
    "I mean... yeah, I guess that could work. But there's this little voice in my head saying it's too risky. But then again, when has playing it safe ever gotten us anywhere?",
    "Let me think, let me think. Okay so we have option A which is safe but boring, and option B which is exciting but terrifying. Classic.",
    "You know what, actually... no. Wait. Yes. Actually, no. Okay, final answer: yes. I'm going with yes.",
    "Here's what's bugging me about this whole situation. It's not that it happened, it's how it happened. Like, the whole thing just feels off somehow.",
    "Oh! Actually, that gives me an idea. What if... no, that's dumb. Or is it? Hold on, let me think this through.",
    "I keep circling back to the same thought and I can't figure out if it's because I'm right or because I'm stubborn. Probably both.",
    "So here's my concern, and tell me if I'm overthinking this, because I might be overthinking this.",
    "Hmm, I want to say yes but something is telling me to wait. I don't know what it is but I've learned to trust that feeling.",
    "Okay so hear me out, this is going to sound weird at first but stay with me. I think it'll make sense by the end. Maybe.",

    # ── Conversational filler & stalling ───────────────────
    "Um, so, the thing is... okay how do I say this? I've been wanting to talk to you about something.",
    "Well, I mean, it's not like... okay, yeah, you're right. It's exactly like that.",
    "So basically, long story short, well actually it's not that short, but the main point is...",
    "I don't know how to say this without it sounding weird, so I'm just going to say it and hope for the best.",
    "Okay so, um, this might come out wrong but I promise my intentions are good.",
    "Right, so, where do I even begin? I guess the beginning would be a good place, wouldn't it?",
    "How do I put this? It's like... you know when... okay, here's a better way to explain it.",
    "I was going to bring this up sooner but the timing never felt right and now it feels kind of random but here goes.",
    "So, yeah, that's um, that's basically where I'm at with the whole thing. Make sense?",
    "Look, I'm just going to come right out and say it because I've been dancing around this for way too long.",

    # ── Active listening responses ─────────────────────────
    "Mhm, yeah, I hear you. Keep going, I'm listening.",
    "Right, right. That makes total sense. And then what happened?",
    "Oh interesting. So what did you do after that?",
    "Yeah, I can see why that would bother you. That's completely understandable.",
    "Wait, so let me make sure I'm following. You went there and then...?",
    "Okay, yeah. I'm with you so far. Go on.",
    "That's a lot. Take your time, there's no rush.",
    "I see, I see. And how did that make you feel?",
    "Got it. So it was more of a situation where you had no choice?",
    "Mmm, yeah. I've been in a similar spot before. It's tough.",

    # ── More extended natural passages ─────────────────────
    "I had this amazing conversation with a stranger on the bus today. We started talking about the weather and somehow ended up discussing the meaning of life. That's the thing about people, you never know what conversation you're going to have until you start talking.",
    "My favorite time of day is right around five or six in the evening, when the light gets all golden and everything looks warm. I think photographers call it golden hour. Whatever they call it, it makes even ordinary things look magical.",
    "I've started this thing where I leave little notes for future me in random places. Like, in a jacket pocket or inside a book I'll read again. So when I find them months later, it's like getting a message from my past self. It's surprisingly comforting.",
    "I was sitting in traffic today and instead of being annoyed, I just turned up the music and sang along. And you know what? It actually turned a frustrating moment into a fun one. I think attitude really is a choice sometimes.",
    "There's this coffee shop I go to where the barista knows my order by heart. And every time she says, the usual? I feel like I belong there. It's such a small thing but it makes me feel known. And isn't that what we all want? To feel known?",
    "I think the hardest part of growing up is realizing that your parents are just people too. They don't have all the answers. They make mistakes. They're figuring it out as they go, same as the rest of us. That realization is kind of scary but also kind of beautiful.",
    "Someone asked me recently what my happiest memory is, and I couldn't pick just one. It's not the big moments that came to mind first. It was the small ones. Laughing in the car with friends. My dad teaching me to ride a bike. Quiet mornings with a good book. The small stuff is the big stuff.",
    "I learned something important this year. You can't control what happens to you, but you can control how you respond. And I know that sounds like something you'd see on a motivational poster, but it's true. The response is where your power is.",
    "I've been collecting moments instead of things lately. Less shopping, more experiencing. And honestly? I'm happier. I don't need another sweater. I need another sunset. Another long walk. Another good conversation. Like this one.",
    "I think everyone should have at least one person in their life who makes them feel like they can be completely themselves. No filter, no performance, just raw, honest, real. If you have that person, hold onto them. If you are that person for someone, you're doing something right.",

    # ── Customer service & helpful tone ────────────────────
    "Oh, absolutely! I'd be happy to help you with that. Let me pull that up real quick.",
    "So what I'm hearing is you need help with your reservation, right? Let me see what I can do.",
    "No worries at all! These things happen. Let's get it sorted out together.",
    "Great question! So the way it works is pretty straightforward, actually.",
    "I totally understand your frustration. That shouldn't have happened and I'm sorry about that.",
    "Let me walk you through it step by step so it makes sense. Ready?",
    "Oh, I see what happened there. Easy fix! Give me one second.",
    "Is there anything else I can help you with? I want to make sure you're all set before we wrap up.",
    "Perfect! So you're all good then? Awesome. Don't hesitate to reach out if you need anything else.",
    "I'm going to put you on a brief hold while I check on that, okay? I'll be right back, I promise.",

    # ── Giving directions & explaining ─────────────────────
    "Okay so you're going to want to take a left at the light, then go straight for about two blocks. You can't miss it, it's the building with the blue awning.",
    "It's really simple, actually. First you open the app, then tap on settings, and it should be right there at the top.",
    "The trick is to not overthink it. Just follow the steps in order and it'll work. Trust me, I messed it up the first three times too.",
    "So basically, the way I'd explain it is like this. Imagine you have a jar, right? And the jar is your time. The big rocks are the important stuff.",
    "Let me break it down for you because when someone explained it to me this way, it finally clicked.",
    "You're almost there! Just one more step. See that button on the right? Click that and you're done.",
    "It sounds more complicated than it actually is. Once you do it once, you'll be like, oh, that's it?",
    "If you get stuck, just text me and I'll walk you through it. Seriously, it's no trouble at all.",
    "The easiest way to remember it is like this. Think of it as a recipe. You wouldn't skip steps in a recipe, right?",
    "Oh! I know a shortcut for that. Instead of doing all those steps, you can just press and hold the button and it does it automatically.",

    # ── Emotional range: sad/vulnerable ────────────────────
    "I don't know why I'm so emotional today. Everything just feels heavier than usual and I can't shake it.",
    "Sometimes I just miss how things used to be. Not because now is bad, just because then was special too.",
    "I had a really hard conversation today and I'm still kind of processing it. I think I need a minute.",
    "It's okay, I'm fine. Well, I'm not fine, but I will be. I just need some time.",
    "I cried in the parking lot today and I'm not even sure why. Sometimes the tears just need to come out.",
    "I miss my grandpa. It's been years but some days it hits me out of nowhere. Today is one of those days.",
    "There are some things you never really get over. You just learn to carry them differently.",
    "I put on a brave face a lot but honestly? Sometimes I'm really struggling behind the scenes.",
    "I feel like I've been running on empty for a while now and I don't know how to refuel.",
    "Can we just sit here quietly for a minute? I don't need words right now, I just need your presence.",

    # ── Emotional range: excited/joyful ────────────────────
    "OH MY GOD! It happened! It actually happened! I can't believe it! Come here, I need to hug someone!",
    "This is the best day ever. I'm not exaggerating. Literally the best day of my entire life!",
    "I am SO pumped right now! Like, I could run a marathon! Okay, not a marathon, but definitely a 5K!",
    "Yes yes yes yes yes! I knew it! I knew it was going to work out! I had a feeling!",
    "I'm literally dancing in my kitchen right now. By myself. No music. Just pure happiness.",
    "Everything is coming together and I'm trying not to jinx it by talking about it but I can't help it!",
    "I feel like I could take on the world right now. Whatever the world throws at me, bring it!",
    "This might be the happiest I've been in a really long time and I want to stay in this feeling forever.",
    "I'm grinning so hard right now that my face hurts. That's how you know it's real joy.",
    "I just want to tell everyone I see about this because I'm bursting. Literally bursting with excitement.",

    # ── Emotional range: annoyed/frustrated ────────────────
    "I'm trying really hard to be patient right now but it is taking everything in me.",
    "You know what drives me absolutely crazy? When people don't listen. Like, I literally just said that.",
    "I've asked three times now and I'm going to lose my mind if I have to ask again.",
    "Why is this so unnecessarily complicated? It should not be this hard. It should not.",
    "I'm not angry, I'm just... disappointed. Which, as we all know, is actually worse.",
    "The amount of hoops I had to jump through for something this simple is honestly insulting.",
    "I just want it to work. That's all I'm asking. Just work. Please. For the love of everything.",
    "If one more thing goes wrong today, I'm going back to bed and starting over tomorrow.",
    "I don't want to complain but I'm going to complain because this is genuinely ridiculous.",
    "Deep breaths. I'm taking deep breaths. It's not working but I'm trying.",

    # ── Sharing good news ──────────────────────────────────
    "Okay, are you sitting down? Because I have the best news and I need you to be seated for this.",
    "Guess what? Guess! No, you'll never guess. Okay, I'll just tell you. I got the job!",
    "So remember that thing I was stressed about? It worked out. It actually worked out perfectly.",
    "I've been dying to tell you this all day. I couldn't say anything until now but oh my god.",
    "You're going to be so happy when I tell you this. Ready? Okay here goes.",
    "I just found out the best news and you're the first person I wanted to tell.",
    "Plot twist! Everything I was worried about? Completely unnecessary. It all went great!",
    "I have an announcement and I want to see your face when I say it. Okay, here it is.",
    "Today I got the email I've been waiting for and I screamed. Like, actually screamed. My neighbors probably think I'm unhinged.",
    "I'm still in shock. Like, is this real? Someone pinch me because I'm pretty sure I'm dreaming.",

    # ── Philosophical & thoughtful ─────────────────────────
    "I wonder if fish know they're wet. Like, if you've never known anything else, does it even register?",
    "Time is so weird when you think about it. A minute can feel like an hour and an hour can feel like a minute.",
    "I think kindness is underrated as a form of intelligence. It takes real awareness to be kind in a difficult moment.",
    "What if the universe is just one big inside joke and we're all in on it but we forgot?",
    "I read that trees communicate through their roots underground. Like, they share nutrients and warn each other about danger. That blew my mind.",
    "The fact that we're on a rock floating through space and we still get upset about stuff like parking tickets is kind of hilarious.",
    "I think every person you meet knows something you don't. Everyone is a teacher if you're willing to learn.",
    "Music is basically organized vibrations that make us feel emotions. When you describe it that way it sounds like magic. And honestly, it kind of is.",
    "I wonder how many times we've been in the same place as someone who will become really important to us but we just haven't met yet.",
    "The universe is, what, fourteen billion years old? And we get like eighty years on this planet. We better make them count.",

    # ── More daily interactions ────────────────────────────
    "Excuse me, sorry, do you know if this bus goes downtown? I always get confused with the routes.",
    "Oh, after you. No really, go ahead. I'm not in a rush.",
    "Is this seat taken? Cool, thanks. I'll just be here reading my book and minding my business.",
    "Hey, quick question. Do you know what time this place closes? I want to make sure I don't get locked in.",
    "Thank you so much! You didn't have to do that but I really appreciate it.",
    "Sorry, I didn't catch your name. Could you say it one more time? I want to make sure I get it right.",
    "Oh, bless you! Sounds like allergies? Yeah, this time of year is brutal for that.",
    "That's a beautiful dog! What breed is it? Oh, a mix? The mixes are always the cutest ones.",
    "Do you mind if I sit here? Every other table is taken and I just need a spot to eat my lunch.",
    "Your garden is gorgeous, by the way. I walk past it every day and it always makes me smile.",
    "Excuse me, I think you dropped this! Yeah, it was right there on the ground. Good thing I saw it.",
    "Oh, we have the same phone case! Great minds think alike, right?",
    "Hi, sorry to bother you, but do you have the time? My phone is dead and I'm supposed to be somewhere.",
    "Want the last slice? No? You sure? Okay, twist my arm. I'll take it then.",
    "I love your earrings! Where did you find those? I've been looking for something exactly like that.",

    # ── Supportive friend dialogue ─────────────────────────
    "Hey, I know things are tough right now but I just want you to know I'm in your corner. Always.",
    "You don't have to have it all figured out right now. Nobody expects that from you. Especially not me.",
    "I'm going to say something and I need you to really hear it, okay? You are enough. Right now, as you are.",
    "Whatever happens, we'll deal with it together. That's what we do. We figure it out.",
    "I know you're scared. And that's okay. Being scared means you care. We'll get through this.",
    "Look at me. You are not a burden. You are never a burden. Don't ever think that.",
    "I'm not going anywhere. You hear me? I'm right here and I'm not going anywhere.",
    "You've been so strong for so long. It's okay to let someone else be strong for you for a bit.",
    "I made you some soup. You don't have to eat it right now but it's there when you're ready.",
    "I cleared my whole afternoon. I'm yours. Whatever you need, wherever you want to go, I'm in.",

    # ── Shopping & errands ─────────────────────────────────
    "Oh this is cute! Wait, how much is it? Hmm. It's cute but is it that cute? You know what, yeah, I'm getting it.",
    "I've been standing in this aisle for fifteen minutes trying to decide between two things that are basically identical.",
    "Do we need milk? I feel like we need milk. I'm getting milk just in case. Better safe than sorry.",
    "I went in for one thing and came out with a full cart. Every single time. I have no self control in there.",
    "The line is so long but I refuse to use self checkout because it always yells at me about unexpected items.",
    "I love a good deal. Like, finding something on sale gives me a rush. Is that weird? Probably. Do I care? No.",
    "I brought my reusable bags but left them in the car. Which is basically the same as not bringing them.",
    "There's something so satisfying about crossing everything off a to do list. I even add things I've already done just to cross them off.",
    "I need to return this but I've been putting it off because returning things feels like a confrontation and I avoid confrontation.",
    "Oh we should check out that new store that opened! I heard it's really good. Well, I saw someone post about it online.",

    # ── Describing things vividly ──────────────────────────
    "The sky right now is this insane shade of pink and orange and purple all mixed together. It looks like a painting. An actual painting.",
    "It smelled like fresh rain and cut grass and something sweet, like flowers maybe. It was one of those smells that makes you stop and breathe deep.",
    "The room was tiny, like barely bigger than a closet, but it was so cozy. String lights everywhere, books piled up, a soft rug on the floor.",
    "The sound of the waves was so constant and rhythmic that it almost felt like a heartbeat. The ocean's heartbeat.",
    "He had the warmest smile. The kind that reaches the eyes. You know those smiles? Where you can tell it's real? That was his smile.",
    "The chocolate cake was so rich it was almost overwhelming. Like, every bite was an event. Dense, fudgy, melt in your mouth perfection.",
    "The fog was so thick this morning that I could barely see ten feet in front of me. It felt like walking through a cloud.",
    "She walked in and the whole room just sort of shifted. Not in a dramatic way, but in a way where you could feel the energy change.",
    "The music was so loud you could feel it in your chest. Like, your ribcage was vibrating. It was intense but in the best way.",
    "The water was crystal clear, like you could see all the way to the bottom. Little fish swimming around, sunlight dancing on the surface.",

    # ── Debating & disagreeing politely ────────────────────
    "See, I hear what you're saying, and I respect it, but I just don't see it that way.",
    "Okay, but consider this. What if the opposite is true? Just entertain it for a second.",
    "I'm going to push back on that a little bit, not to be difficult, but because I think there's another angle.",
    "We're going to have to agree to disagree on this one. And that's totally fine. That's what makes us interesting.",
    "I think you make a fair point, but here's where I get stuck with that logic.",
    "Wait, but doesn't that contradict what you said earlier? Help me connect the dots here.",
    "I love that we can disagree and still be cool about it. Not everyone can do that.",
    "Fair enough. You've given me something to think about. I might come around to your side eventually.",
    "Okay, you win this round. But I reserve the right to bring it up again later when I have better arguments.",
    "That's a bold take and honestly I kind of admire the confidence even though I think you're wrong.",

    # ── Winding down & saying goodbye ──────────────────────
    "Well, I should probably head out. But this was so nice. Really, really nice.",
    "I don't want to go but I have to. Can we do this again soon? Like, really soon?",
    "Okay, one more story and then I really have to leave. I keep saying that but I mean it this time.",
    "Walk me out? I always feel like the conversation is better on the way to the door anyway.",
    "Drive safe, okay? Text me when you get home so I know you made it.",
    "This was exactly what I needed. A good conversation and a good friend. You checked both boxes.",
    "Oh gosh, look at the time! I completely lost track. See, that's how I know we had a good talk.",
    "Alright, I'm gonna go before I start another topic. Because I will. You know I will.",
    "Hug? Come here. That was a good one. Okay, for real this time. I'm going. Bye! Love you! Bye!",
    "Until next time, my friend. Take care of yourself and don't be a stranger, okay?",

    # ── Reassuring someone on the phone ────────────────────
    "Hey, hey, slow down. Take a breath. Okay, now tell me what happened. Start from the beginning.",
    "I'm right here, okay? I'm not hanging up. Take all the time you need.",
    "That sounds really scary but you're safe now, right? Okay good. That's what matters.",
    "Listen to me. You did the right thing. You absolutely did the right thing. Don't second guess yourself.",
    "I know it feels like the end of the world right now but I promise you it's not. This will pass.",
    "I'm going to stay on the phone with you until you feel better. I don't care how long it takes.",
    "Can you do something for me? Just look around and tell me five things you can see. It helps, trust me.",
    "You're stronger than you think you are. I mean that. You've been through worse and you're still here.",
    "It's going to be okay. And I'm not just saying that to say it. I genuinely believe it's going to be okay.",
    "I love you, you know that? Whatever this is, we'll figure it out. Together. Like we always do.",

    # ── Random fun & quirky ────────────────────────────────
    "If I were a superhero, my power would definitely be being able to fall asleep anywhere. Instantly. On command.",
    "I just had a staring contest with myself in the mirror and I lost. How does that even work?",
    "My life motto is basically just winging it and hoping for the best, and so far it's been surprisingly effective.",
    "I wonder what my dog thinks about all day. Like, is he having deep thoughts or is it just squirrel, nap, food, repeat?",
    "If I could have any job in the world, I think I'd be a professional sunset watcher. Is that a thing? It should be a thing.",
    "I accidentally made eye contact with someone through a window and now we're basically in a relationship.",
    "My spirit animal is a sloth. Not because I'm lazy, but because I believe in moving with intention. Slowly. Very slowly.",
    "I tried to wink at someone and instead I just blinked aggressively with one eye. Nailed it.",
    "If aliens came to Earth and asked me to explain humanity, I'd just show them a video of people at IKEA on a Saturday.",
    "I put my shirt on inside out today and didn't notice until someone pointed it out. I said it was a fashion statement.",

    # ── Final batch: mixed conversational ──────────────────
    "Oh! Before I forget, I wanted to ask you something. It's been on my mind all week.",
    "You have no idea how much I needed to hear that today. Your timing is impeccable as always.",
    "I've been replaying this conversation in my head and I keep thinking of better things I should have said.",
    "Can we talk about something light? My brain needs a break from all the heavy stuff.",
    "You always have the best energy. Like, I leave our conversations feeling recharged. That's rare.",
    "I tried to explain this to someone else and they didn't get it at all. But I knew you would understand.",
    "That might be the most relatable thing anyone has ever said to me. I feel seen right now.",
    "Okay, rapid fire. Favorite color, favorite season, favorite ice cream flavor. Go!",
    "You know what, I changed my mind. I'm going for it. Life's too short to play it safe all the time.",
    "I think this is the beginning of something really good. I can feel it. Can you feel it too?",
    "That was such a perfect way to put it. I'm going to remember that. I might even write it down.",
    "Hold that thought because I need to get a snack. I can't have deep conversations on an empty stomach.",
    "We've been talking for two hours and it felt like twenty minutes. That's the sign of a truly great conversation.",
    "Okay, last thing, and then I promise I'll stop talking. Well, probably. Okay, no promises. But listen.",
    "I'm smiling so hard right now. Like, if you could see my face. This is pure, genuine, ear to ear happiness.",

    # ── Absolute last batch to max credits ─────────────────
    "Oh wait, one more thing. I keep saying one more thing but this is actually the last one. I think.",
    "You ever get that feeling where something just clicks? Like puzzle pieces snapping together? That's what just happened.",
    "I wrote you a little note. Don't open it now, open it later when you need a pick me up.",
    "This tastes like summer. I know that sounds weird but there are foods that taste like seasons and this is one of them.",
    "My favorite sound in the world is rain on a tin roof. Or maybe laughter. Actually, definitely laughter.",
    "I just realized we've known each other for years and I still learn new things about you. That's pretty special.",
    "Oh, you startled me! I was completely zoned out. I do that sometimes. Just go to another planet in my head.",
    "I think I left my phone in the car. Actually, no, it's in my pocket. Crisis averted.",
    "That was a mic drop moment and you didn't even realize it. You just casually dropped wisdom like it was nothing.",
    "I love those lazy Sunday afternoons where you have absolutely nothing to do and nowhere to be. Pure bliss.",
    "I'm one of those people who gets emotional at graduations even when I don't know anyone graduating. The potential, the pride, it just gets to me.",
    "You want to know what my comfort movie is? Don't judge me. Okay, you're going to judge me. But I don't care.",
    "I think about conversations days after they happen. Like, I'll be in the shower and suddenly think of the perfect response three days too late.",
    "The best surprises are the ones you don't see coming at all. The ones that catch you completely off guard in the best way.",
    "I love how passionate you get about this stuff. Your whole face lights up and your voice changes and it's the most authentic version of you.",
    "There's a crack in everything, that's how the light gets in. I read that somewhere and it stuck with me. It's about imperfection being beautiful.",
    "I've been meaning to learn how to dance. Not professionally, just enough to not embarrass myself at weddings.",
    "You know those mornings where the sun comes through the curtains just right and everything glows gold? I had one of those today and it set the tone for the whole day.",
    "I'm a firm believer that dessert should come first sometimes. Life is uncertain. Eat the cake.",
    "There's something about handwritten letters that hits different than texts or emails. The effort, the permanence, the fact that someone sat down and wrote it just for you.",
    "I sneezed while drinking coffee and now it's everywhere. The ceiling. My shirt. The wall. I didn't know that was physically possible.",
    "My phone autocorrected something to the most inappropriate word possible and I sent it to my boss. I'm currently updating my resume.",
    "Okay here's a controversial take. Pineapple absolutely belongs on pizza. I will debate anyone on this. Any time. Any place.",
    "I think the world would be a better place if people spent more time asking questions and less time assuming they know the answers.",
    "There are seven billion people on this planet and somehow I ended up knowing you. The odds of that are insane. And I'm really glad the universe worked it out.",
    "I keep a gratitude journal and today's entry is just this conversation. That's it. That's the whole entry.",
    "If I could bottle this feeling right now, I'd keep it on my shelf and open it on rainy days when I need a reminder that life is good.",
    "Do you believe in parallel universes? Because somewhere out there, there's a version of us having this exact same conversation. And they're probably having just as good a time.",
    "I want to age like my grandmother. Gracefully, joyfully, with a sharp wit and an even sharper sense of humor. That woman is my hero.",
    "Alright, this is it. For real this time. The actual, final, absolute last thing I'm going to say. Thank you for being you. Okay, now I'm done. Maybe.",
]
