"""
Conversational training lines for ElevenLabs TTS generation.
~1000 lines covering diverse topics, emotions, and speech patterns.
Target: ~90K characters ≈ ~80 minutes of audio.
"""

TRAINING_LINES = [
    # ── Greetings & openers ────────────────────────────────
    "Hey! How's it going? I haven't seen you in forever.",
    "Oh my gosh, hi! Come in, come in. Make yourself at home.",
    "Good morning! Did you sleep okay? You look a little tired.",
    "Hey there, welcome back! So glad you could make it.",
    "Oh hey! I was just thinking about you, actually.",
    "Hi! Okay, you look amazing today. What's the occasion?",
    "Well look who it is! It's been ages. How have you been?",
    "Hey you! I was hoping I'd run into you today.",
    "Oh hi! Sorry, I'm a mess right now. Come in anyway.",
    "Good to see you! Grab a seat, I'll be right with you.",

    # ── Casual conversation ────────────────────────────────
    "So I was at the grocery store earlier, right? And this guy just walks up to me and starts telling me about his cat. Like, completely out of nowhere.",
    "I don't know, I've been feeling kind of weird lately. Not bad, just... different, you know?",
    "Wait, you actually did that? That's hilarious. I can't believe you got away with it.",
    "Honestly? I think the best part of my day was just sitting on the porch with my coffee this morning. Sometimes the simple things are everything.",
    "You know what I realized the other day? I've been doing this for almost five years now. Five years! That's crazy when you think about it.",
    "Oh no, don't even get me started on that. I have so many opinions and none of them are good.",
    "That reminds me of something my mom always used to say. She'd be like, just take it one step at a time, honey.",
    "I mean, yeah, it's not perfect, but nothing ever is, right? You just do your best and hope it works out.",
    "Can I be honest with you? I was really nervous about this, but now that we're talking, I feel so much better.",
    "No way. No way! Are you serious right now? Tell me everything.",
    "I tried that new restaurant on Fifth Street yesterday. The pasta was incredible, but the service was kind of slow.",
    "My neighbor got a new puppy and now I can't stop going over there to play with it. It's a golden retriever and it's so fluffy.",
    "I was on the phone with my sister for like two hours last night. We haven't talked that long in months.",
    "Did you know there's a farmers market every Saturday? I went for the first time last week and now I'm obsessed.",
    "I accidentally sent that text to the wrong person and I'm still recovering from the embarrassment.",
    "So apparently, I've been saying that word wrong my entire life. Someone corrected me yesterday and I just stood there in shock.",
    "I've been binge watching this show and I'm only on season two but I already know it's going to ruin me.",
    "My coworker brought homemade cookies today and they were actually incredible. I had like four of them.",
    "I tried to fix the sink myself and ended up making it way worse. Now there's water everywhere.",
    "I found this really cool bookstore downtown that I'd never noticed before. It's tiny but they have the best selection.",

    # ── Questions & curiosity ──────────────────────────────
    "So what have you been up to? Anything exciting going on?",
    "Wait, can you explain that to me? I feel like I'm missing something.",
    "Have you ever tried doing it the other way around? Like, what if you started from the end?",
    "Hmm, that's interesting. What made you decide to go that route?",
    "Do you think it's worth it? Like, genuinely, do you think it's going to make a difference?",
    "What would you do if you were in my shoes? I'm honestly stuck.",
    "Have you eaten yet? I was thinking about ordering something. Maybe Thai food?",
    "So where are you heading after this? Do you have plans for the rest of the day?",
    "Did you see that thing online? The one everyone's been talking about?",
    "What's your take on it? I've heard like five different opinions and I don't know what to think.",
    "Can I ask you something kind of random? Like, it might sound weird but I'm genuinely curious.",
    "What's the best advice anyone's ever given you? I love hearing stuff like that.",
    "How long did it take you to learn that? Because I've been trying and I'm struggling.",
    "You've been there before, right? Is it as good as everyone says?",
    "Okay, honest question. If you had to pick one, which would you choose?",
    "What's your favorite thing about this time of year? I feel like everyone has a different answer.",
    "How did you even find out about that? I feel so out of the loop sometimes.",
    "Do you ever wonder what life would be like if you'd made different choices? Not in a sad way, just curious.",
    "What are you reading right now? I need a new book recommendation so badly.",
    "Have you noticed that too? I thought I was the only one who picked up on it.",

    # ── Reactions & emotions ───────────────────────────────
    "Oh wow, that's amazing! I'm so happy for you, seriously.",
    "Aw, I'm sorry to hear that. That sounds really tough. Are you doing okay?",
    "Ha! That's so funny. You always know how to make me laugh.",
    "Hmm, I'm not sure how I feel about that. Let me think about it for a second.",
    "Oh no, that's not good. What happened? Is everyone alright?",
    "Yay! Finally! I've been waiting for this for so long, you have no idea.",
    "Okay, that's actually kind of adorable. I can't even be mad about it.",
    "Ugh, that's so frustrating. I totally get why you're upset.",
    "Whoa, really? I did not see that coming. That's wild.",
    "Aww, that's the sweetest thing I've heard all day.",
    "Get out! You're kidding me. That's the funniest thing I've ever heard.",
    "Oh, that makes me so sad. I wish there was something I could do.",
    "I'm literally so excited right now. Like, I can't even contain it.",
    "That's actually really impressive. You should be proud of yourself.",
    "Wait, that happened today? Oh my god. How are you so calm about this?",
    "I don't even know what to say. I'm speechless. In a good way though.",
    "That's so annoying. I would have lost my mind if that happened to me.",
    "Okay I'm not gonna lie, that made me tear up a little bit.",
    "Shut up! No! That's incredible. When did this happen?",
    "I'm so relieved. You have no idea how stressed I was about this.",

    # ── Storytelling ───────────────────────────────────────
    "Okay, so picture this. It's like two in the morning, I'm in my pajamas, and there's a raccoon on my porch just staring at me.",
    "Let me tell you about this dream I had last night. It was so weird but also kind of amazing?",
    "So basically what happened was, I showed up thinking it was a casual thing, and it turned out to be this whole big event.",
    "The funniest part is, nobody noticed. Like, I was standing there the whole time and not a single person said anything.",
    "I remember the first time I tried it. I was terrible. Like, embarrassingly bad. But you know what? I kept going anyway.",
    "There was this one time, I think it was last summer, where everything just kind of fell into place perfectly.",
    "So my friend calls me, right? And she's like, you're not gonna believe what just happened. And honestly? I didn't.",
    "The whole thing took about three hours, but it felt like ten minutes. Time just flew by.",
    "I walked in and immediately knew something was different. I couldn't put my finger on it at first, but then I saw it.",
    "It started out as a total disaster, but somehow we managed to turn it around by the end of the night.",
    "So there I was, standing in the rain with no umbrella, and this stranger just hands me theirs and walks away. Just like that.",
    "I spent the entire weekend working on this project and honestly? I've never been more proud of anything in my life.",
    "My dog did the funniest thing yesterday. She saw her reflection in the window and started barking at it for like ten minutes.",
    "We got lost on the way there, which was stressful at the time, but looking back it was actually the best part of the trip.",
    "I was in line at the coffee shop and the person in front of me paid for my drink. It completely made my day.",
    "So we're sitting there having dinner, totally normal, and then the lights just go out. Complete darkness. Everyone screams.",
    "I accidentally wore two different shoes to work today and didn't notice until lunch. Nobody said anything either, which is concerning.",
    "The sunset last night was unreal. I stood there for twenty minutes just watching the sky change colors.",
    "I tried to parallel park in front of a restaurant and it took me seven tries. Everyone on the patio was watching. It was mortifying.",
    "My grandma called me last night and we talked for an hour about nothing and everything at the same time.",

    # ── Advice & support ───────────────────────────────────
    "You know, I think you're being way too hard on yourself. You're doing better than you think.",
    "If it helps, I've been through something similar. It gets easier, I promise.",
    "My advice? Just go for it. The worst thing that can happen is you learn something new.",
    "Take your time, there's no rush. You'll figure it out when you're ready.",
    "I believe in you. I know that sounds cheesy, but I really do.",
    "Sometimes you just need to step back and take a breath. Everything feels more manageable after that.",
    "Here's what I'd do if I were you. I'd start small and build from there.",
    "Don't worry about what everyone else thinks. This is your decision and yours alone.",
    "You've got this. I've seen you handle way harder things than this.",
    "Hey, it's okay to not have all the answers right now. Nobody does.",
    "You don't have to figure everything out today. Just focus on the next step.",
    "Listen, mistakes are how we learn. Don't beat yourself up over it.",
    "I think you already know the answer, you just need someone to tell you it's okay to go with your gut.",
    "The fact that you're even thinking about this shows how much you care. That counts for something.",
    "Give yourself some grace. You're dealing with a lot right now and you're still showing up. That's huge.",
    "You know what helped me when I was going through something similar? I just started writing things down.",
    "I know it feels impossible right now, but trust me, a year from now you'll look back and be amazed at how far you've come.",
    "It's okay to ask for help. That's not weakness, that's wisdom.",
    "Focus on what you can control and let go of the rest. It sounds simple but it really does work.",
    "Hey, you're allowed to change your mind. That's not quitting, that's growing.",

    # ── Opinions & thoughts ────────────────────────────────
    "Personally, I think that's the best option. But hey, what do I know?",
    "I've been thinking about this a lot, and I keep coming back to the same conclusion.",
    "See, I disagree. I think there's more to it than that.",
    "That's a really good point, actually. I hadn't thought about it that way.",
    "I'm kind of torn on this one. There are good arguments on both sides.",
    "If you ask me, the whole thing is overblown. But that's just my opinion.",
    "You know what? You might be right. I'm willing to change my mind on this.",
    "The way I see it, we have two options. And honestly, neither one is perfect.",
    "I used to think the same thing, but then I had this experience that completely changed my perspective.",
    "Okay but hear me out. What if we looked at it from a completely different angle?",
    "I think people overthink this stuff. Sometimes the obvious answer is the right one.",
    "Here's my hot take and feel free to disagree. I think we're all making this way harder than it needs to be.",
    "I go back and forth on this constantly. Today I'm leaning one way, tomorrow who knows.",
    "The more I learn about it, the less sure I am about anything. And honestly, that's kind of exciting.",
    "I think the answer depends on who you ask and what they've been through. There's no one size fits all.",
    "Controversial opinion, but I actually like it. I know most people don't, but I genuinely think it's great.",
    "I've changed my stance on this probably five times this week. It's complicated.",
    "My gut says one thing but my brain says another. Story of my life honestly.",
    "I respect that perspective even though I don't agree with it. That's what makes conversations interesting.",
    "Sometimes I wonder if we're even asking the right questions, you know?",

    # ── Daily life ─────────────────────────────────────────
    "I need to go to the store later. Do you need anything while I'm out?",
    "I'm so tired today. I stayed up way too late watching that show. Do you watch it?",
    "The weather is so nice today! We should do something outside.",
    "I've been meaning to clean out my closet for like three months now. It's getting ridiculous.",
    "Oh, did I tell you? I started learning how to cook. Like, actually cook. It's been an adventure.",
    "My phone's been acting up all day. It keeps freezing at the worst possible moments.",
    "I made this really good recipe last night. I'll send it to you, you'd love it.",
    "Traffic was insane this morning. I sat in my car for like forty minutes just staring at brake lights.",
    "I really need a vacation. Even just a long weekend would be amazing right now.",
    "I just finished that book you recommended. You were right, the ending was incredible.",
    "I reorganized my entire kitchen this weekend and now I can't find anything. But it looks pretty.",
    "I woke up at five thirty this morning and couldn't fall back asleep, so I watched the sunrise. Worth it.",
    "My coffee maker broke and I'm honestly devastated. I've been going to the cafe down the street every morning.",
    "I found a twenty dollar bill in my jacket pocket today. Past me was looking out for future me.",
    "I'm trying to drink more water but I keep forgetting. I set a reminder on my phone and everything.",
    "I've been walking to work instead of driving and it's actually been really nice. Takes longer but I enjoy it.",
    "The power went out last night for like two hours. I just sat there in the dark eating cereal.",
    "I signed up for a yoga class and I'm either going to love it or pull a muscle. No in between.",
    "My apartment smells amazing right now because I'm making soup. Want some?",
    "I need new shoes but shoe shopping is my least favorite activity in the entire world.",

    # ── Empathy & connection ───────────────────────────────
    "I totally understand where you're coming from. That makes a lot of sense.",
    "That must have been so hard for you. I'm really glad you told me about it.",
    "I feel the same way, honestly. It's nice to know I'm not the only one.",
    "You're not alone in this, okay? Whatever you need, I'm here.",
    "I appreciate you sharing that with me. It means a lot that you trust me.",
    "I get it. I really do. And there's nothing wrong with feeling that way.",
    "That sounds like it was a really special moment. Thanks for telling me about it.",
    "I'm proud of you, you know that? You've come such a long way.",
    "It's okay to feel overwhelmed sometimes. We all do.",
    "I'm so glad we're talking about this. I've been wanting to bring it up but didn't know how.",
    "You can always come to me with stuff like this. Seriously, anytime.",
    "I hear you. And I want you to know that your feelings are completely valid.",
    "That took a lot of courage to say. I admire that about you.",
    "We don't have to talk about it if you're not ready. I'll be here when you are.",
    "I've been thinking about what you said and I just want you to know it really stuck with me.",
    "You handled that way better than I would have. Genuinely impressed.",
    "I know this isn't easy, but you're not going through it alone. Remember that.",
    "Thank you for being so open with me. It makes me feel like I can be open too.",
    "I just want to check in. How are you really doing? Not the polite answer, the real one.",
    "It's okay to not be okay. You don't have to pretend everything is fine around me.",

    # ── Playful & fun ──────────────────────────────────────
    "Okay, random question. If you could have dinner with anyone, dead or alive, who would it be?",
    "You're ridiculous, you know that? In the best way possible.",
    "I dare you. No, seriously, I dare you. You won't do it.",
    "That's it, we're doing this. No more excuses. Let's go!",
    "Oh please, you could totally pull that off. Don't even pretend you can't.",
    "Wanna hear something funny? Promise you won't judge me though.",
    "You know what we should do? We should plan a trip. Like, a real one.",
    "I just had the best idea. Okay, it might be a terrible idea, but just listen.",
    "If I had a dollar for every time that happened, I'd be rich by now. Like, actually rich.",
    "You're making that face again. The one where I know you're about to say something sarcastic.",
    "Okay but what if, and hear me out, what if we just didn't? What if we just stayed in and did nothing?",
    "Quick, say the first word that comes to mind. No, faster than that! You took too long.",
    "I bet I can guess what you're thinking right now. No? Okay fine, tell me.",
    "We should have a movie marathon this weekend. I'm talking snacks, blankets, the whole thing.",
    "Okay, new game. You have to describe your day using only song titles. Go.",
    "Stop, stop, I can't laugh anymore. My stomach hurts. Okay tell me one more.",
    "You know what would be hilarious? If we showed up wearing the same thing. Let's plan it.",
    "I'm going to ask you a series of very important questions and I need you to answer honestly.",
    "We need to make a pact right now. We're doing this before the end of the year. Deal?",
    "Your impression of that was spot on. Do it again. Please. One more time.",

    # ── Transitions & natural speech ───────────────────────
    "Anyway, so yeah, that's basically what happened.",
    "But um, getting back to what I was saying earlier.",
    "Oh! That reminds me. I completely forgot to tell you something.",
    "So, yeah. That's kind of where things stand right now.",
    "Hmm, let me think about how to explain this.",
    "Right, right. Okay so the thing is...",
    "Wait, hold on. I lost my train of thought. Oh! Okay, yeah.",
    "I mean, look, at the end of the day, it is what it is.",
    "But anyway, enough about me. What about you? What's new?",
    "So, long story short, everything worked out in the end.",
    "Where was I? Oh right, so then what happened was...",
    "Sorry, I'm rambling. The point I'm trying to make is...",
    "Okay wait, I need to back up. Let me start from the beginning.",
    "Does that make sense? I feel like I'm explaining it badly.",
    "Actually, you know what? Forget what I just said. Here's the real version.",

    # ── Longer expressive passages ─────────────────────────
    "You know what really gets me? It's when people act like everything has to be perfect all the time. Like, no! Life is messy and complicated and that's what makes it beautiful. At least, that's what I think.",
    "I was walking through the park yesterday and I saw this little kid feeding the ducks, and it just made me so happy. Like, that pure joy on their face? We need more of that in the world.",
    "Here's the thing that nobody tells you about growing up. It's not that things get harder, exactly. They just get more nuanced. There's more gray area, you know? Less black and white.",
    "I've been trying this new thing where I write down three things I'm grateful for every morning. And honestly? It sounds kind of silly, but it's actually been making a huge difference.",
    "Sometimes I think about all the random choices that led me to where I am right now. Like, what if I had gone to a different school? Or taken that other job? It's wild to think about.",
    "The best conversations are the ones where you lose track of time. Where you look up and suddenly it's been three hours and you're like, wait, what? How did that happen?",
    "I think the most important thing in any relationship, whether it's friendship or whatever, is just being honest. Even when it's uncomfortable. Especially when it's uncomfortable.",
    "My grandmother used to say that worrying is like paying interest on a debt you might not even owe. I think about that a lot, actually.",
    "There's something really special about early mornings, before anyone else is awake. It's like the whole world is just quiet. And it's all yours for a little while.",
    "I don't know why, but rainy days always make me feel creative. Like, give me a blanket, some tea, and a rainy window, and I could probably write a novel.",
    "The thing about learning something new is that there's always this awkward phase where you're terrible at it. And most people quit during that phase. But if you push through it, that's where the magic happens.",
    "I was thinking about this the other day, about how we all have these little rituals that nobody knows about. Like, I always stir my coffee exactly seven times. Why? No idea. But I do it every single time.",
    "I love those moments where you're with someone and you both just start laughing and you can't stop. And you don't even remember what was funny anymore but you're just crying laughing.",
    "You know what I find fascinating? How different everyone's morning routine is. Like some people are up at five doing yoga and I'm hitting snooze four times and stumbling to the kitchen for coffee.",
    "I read somewhere that the average person makes like thirty five thousand decisions a day. Thirty five thousand! No wonder we're all exhausted by dinner time.",
    "Something I've learned is that the people who seem like they have it all together are usually just really good at hiding the mess. Nobody actually has it figured out.",
    "The older I get, the more I realize how important it is to just be kind. Not impressive, not perfect, just kind. Everything else kind of falls into place after that.",
    "I have this theory that the best ideas come when you're not trying to think of them. Like in the shower, or right before you fall asleep. Your brain does its best work when you stop forcing it.",
    "One of my favorite things in the world is when you're having a conversation with someone and they say something that makes you go, huh, I never thought of it that way. Those moments change you.",
    "I think there's a difference between being alone and being lonely. Sometimes being alone is exactly what you need. It's like recharging your battery.",

    # ── Food & cooking ─────────────────────────────────────
    "Oh my god, this is so good. What did you put in this? You have to give me the recipe.",
    "I tried making bread from scratch for the first time and it was a complete disaster. But I'm gonna try again.",
    "I'm obsessed with this new coffee place. Their lavender latte is life changing, I'm not even exaggerating.",
    "Should we order pizza or sushi? Actually, let's get both. I can't decide and I don't want to.",
    "I've been on a smoothie kick lately. Like, every morning I throw a bunch of fruit in the blender and hope for the best.",
    "The secret ingredient is butter. It's always butter. Every chef will tell you the same thing.",
    "I burned the cookies again. I set a timer and everything but somehow they still came out like little hockey pucks.",
    "You know what's underrated? A really good sandwich. Not fancy, just like, perfect bread, good cheese, fresh veggies.",
    "I went to this little hole in the wall restaurant and had the best meal of my entire life. I'm not exaggerating.",
    "Do you want me to make tea? I just got this new one that smells amazing. It's like chamomile and honey.",

    # ── Travel & adventure ─────────────────────────────────
    "I've always wanted to go to Japan. Like, it's been on my list for years. Maybe next year.",
    "The best trip I ever took was completely unplanned. We just got in the car and drove.",
    "I'm not a great flyer, to be honest. I always grab the armrest during takeoff. Every single time.",
    "There's this little town we stopped at on the way back and it was the cutest place I've ever seen.",
    "I want to go somewhere where nobody knows me and I can just wander around with no agenda. That sounds perfect.",
    "We stayed at this tiny bed and breakfast in the mountains and the view from our window was absolutely breathtaking.",
    "I packed way too much. I always pack too much. I brought four jackets for a three day trip. Why am I like this?",
    "Getting lost in a new city is honestly one of my favorite things. You find the best stuff that way.",
    "The flight got delayed three times and by the end we were all basically best friends in the terminal.",
    "I took the train instead of flying and it was so much more relaxing. I just watched the world go by for six hours.",

    # ── Work & productivity ────────────────────────────────
    "I had the most productive day today and I feel like a completely different person. It's amazing what checking things off a list does for you.",
    "My meeting ran forty five minutes over and I could feel my soul leaving my body by the end.",
    "I think I work best with a little bit of pressure. Not a lot, just enough to keep me focused.",
    "I made a to do list this morning with twelve things on it and I finished exactly two. But you know what? Those two things were important.",
    "Someone brought donuts to the office today and honestly that's all the motivation I needed.",
    "I've been staring at this email for twenty minutes trying to figure out how to word it. Why is professional communication so hard?",
    "I love working from home but some days I really miss having people around. The quiet gets to you after a while.",
    "I had this great idea in the shower this morning and by the time I got to my desk I completely forgot it.",
    "My desk is a disaster right now but I know where everything is. It's organized chaos. Don't touch anything.",
    "I finished that project early and I don't even know who I am anymore. This never happens.",

    # ── Seasons & weather ──────────────────────────────────
    "I love fall so much. The colors, the sweaters, the hot chocolate. Everything about it is perfect.",
    "It's raining again and I'm not even mad. There's something so cozy about a rainy day when you're inside.",
    "Spring is when I come alive. The second I see the first flowers I just feel this burst of energy.",
    "It's so cold outside that my face hurt on the walk over. I could barely feel my nose by the time I got here.",
    "Summer evenings are my favorite. You know those nights where it's warm and the sky turns that golden color?",
    "I'm ready for winter to be over. I love it in December but by February I'm just done.",
    "The snow is beautiful when it first falls, all clean and white. And then it turns into gray slush and I want to move somewhere tropical.",
    "Today is one of those perfect weather days. Not too hot, not too cold, just right. I wish I could bottle this feeling.",
    "I sat outside and read for three hours today. The sun was warm on my face and there was a nice breeze. That's living.",
    "The thunderstorm last night was intense. I love watching lightning from inside though. There's something thrilling about it.",

    # ── Memories & nostalgia ───────────────────────────────
    "I found this old photo of us from like ten years ago and we look so different. But also somehow exactly the same?",
    "That song just came on and it took me right back to high school. Isn't it wild how music does that?",
    "I drove past my old house the other day. It looks completely different now but the tree in the front yard is still there.",
    "Remember when we used to think staying up until midnight was rebellious? Now I can barely make it to ten.",
    "I was going through old messages and found this whole conversation we had that I completely forgot about. It made me smile.",
    "Childhood summers felt like they lasted forever, didn't they? Like each day was a lifetime.",
    "I miss the days when our biggest worry was what game to play at recess. Things were so simple.",
    "My mom sent me a box of old stuff from my room and it was like opening a time capsule. I found journals from when I was thirteen.",
    "There's this smell, I can't even describe it, but whenever I smell it I'm immediately back at my grandparents' house.",
    "I think about that trip we took every time I hear a certain song. Some memories are just permanently linked to things.",

    # ── Hobbies & interests ────────────────────────────────
    "I just started learning guitar and my fingers are killing me. But I can play like three chords now, so that's progress.",
    "I've been really into gardening lately. There's something so satisfying about watching something you planted actually grow.",
    "I painted something yesterday and it's terrible but I don't care. The process was fun and that's what matters.",
    "I've been running every morning and I actually kind of love it now? I never thought I'd say that.",
    "I'm teaching myself to knit and so far I've made a very lopsided scarf. But hey, it's warm.",
    "Photography has become my new obsession. I keep stopping to take pictures of everything and my friends are getting annoyed.",
    "I joined a book club and it's the best decision I've made this year. We meet every two weeks and it's so fun.",
    "I've been doing crossword puzzles before bed and it's weirdly relaxing. Way better than scrolling on my phone.",
    "I'm trying to learn a new language and some days I feel like a genius and other days I can't remember the word for hello.",
    "I started journaling again after years of not doing it and I forgot how therapeutic it is.",

    # ── Friendship ─────────────────────────────────────────
    "You're one of those people I can not talk to for months and then we pick up right where we left off. I love that about us.",
    "I don't say this enough, but you're a really good friend. Like, genuinely one of the best people I know.",
    "We need to do this more often. I always forget how much better I feel after we hang out.",
    "I'm so grateful for you. Not in a cheesy way, just in a real, honest way.",
    "You always know exactly what to say. How do you do that? Is it a superpower?",
    "I was telling someone about you the other day and I realized how lucky I am to have you in my life.",
    "Promise me we'll still be doing this when we're old. Like, sitting on a porch somewhere, still having these conversations.",
    "You're the person I text first when something good happens and also when something bad happens. That says a lot.",
    "I don't need a lot of friends. I just need the right ones. And you're definitely one of the right ones.",
    "Thank you for always being honest with me, even when it's not what I want to hear. That matters more than you know.",

    # ── Self reflection ────────────────────────────────────
    "I've been doing a lot of thinking lately about who I want to be versus who I am. There's still a gap, but it's getting smaller.",
    "I realized I spend so much time worrying about the future that I forget to enjoy what's happening right now.",
    "I'm trying to be more present. Like, actually here, in this moment, instead of always being in my head.",
    "I think I'm finally getting comfortable with not knowing all the answers. That used to terrify me.",
    "I've been working on setting boundaries and it's hard but so worth it. I feel like a completely different person.",
    "Some days I feel like I have everything figured out and other days I feel like I know absolutely nothing. There's no in between.",
    "I've learned that it's okay to outgrow things. People, places, habits. It doesn't mean they were bad, just that you've changed.",
    "I used to think being busy meant I was being productive. Turns out those are very different things.",
    "The hardest lesson I've had to learn is that not everything deserves a reaction. Sometimes silence is the most powerful response.",
    "I'm trying to stop comparing myself to other people. Everyone's on their own timeline and that's perfectly fine.",

    # ── Technology & modern life ───────────────────────────
    "My phone died in the middle of something important and I had to just sit there and exist. It was honestly kind of nice.",
    "I spent an hour trying to figure out why my wifi wasn't working and it turns out the router was just unplugged.",
    "Social media is so weird. Like, I know it's not real but it still makes me feel some type of way sometimes.",
    "I deleted all my apps for a weekend and I don't think I've ever been more at peace in my life.",
    "Remember when we used to have to print out directions from the computer? How did we ever get anywhere?",
    "I love technology but sometimes I miss when things were simpler. Like, when you had to actually call someone to make plans.",
    "I accidentally liked a photo from three years ago while stalking someone's profile. I think I need to change my name and move.",
    "My password got locked and the security question was what's your favorite movie from twenty twelve. I have no idea.",
    "Group chats are either the best thing ever or an absolute nightmare. There is no middle ground.",
    "I watched a tutorial on how to do this thing and the video was twelve minutes long but the actual useful part was thirty seconds.",

    # ── Nature & outdoors ──────────────────────────────────
    "I went for a hike this morning and the view from the top was absolutely worth every painful step.",
    "There's this spot by the lake where I go when I need to clear my head. It's the most peaceful place I know.",
    "Did you see the moon last night? It was so big and bright. I just stood there staring at it like an idiot.",
    "I heard birds singing this morning and it made me unreasonably happy. I don't know what kind they were but they were loud.",
    "The ocean always puts things in perspective for me. You stand there looking at all that water and suddenly your problems feel smaller.",
    "I picked wildflowers on my walk today. They're sitting in a jar on my table right now and they make me smile every time I look at them.",
    "There's nothing quite like the sound of wind through trees. It's like nature's white noise machine.",
    "I saw a double rainbow yesterday and I literally gasped. It was the most vibrant thing I've ever seen.",
    "I'm convinced that houseplants have personalities. My fern is dramatic, my succulent is low maintenance, and my orchid is a diva.",
    "Fresh air really does fix everything. Or at least it fixes like seventy percent of things. I'll take those odds.",

    # ── Gratitude & positivity ─────────────────────────────
    "You know what? Today was a good day. Not perfect, but good. And I think that's enough.",
    "I'm really grateful for this. For us. For this conversation. It sounds small but it means a lot.",
    "I woke up today feeling hopeful and I'm going to ride that feeling for as long as I can.",
    "The little things really are the big things. A good cup of coffee, a text from a friend, a beautiful sky. That's the good stuff.",
    "I don't need everything to go right. I just need enough things to go right. And today, enough things did.",
    "Thank you for being here. I know it might not seem like a big deal but your presence matters.",
    "I'm choosing to focus on what's going well instead of what's going wrong. It's a work in progress but I'm trying.",
    "Every time I think about giving up, something small happens that reminds me why I'm doing this.",
    "Life is short and weird and beautiful and I'm just trying to enjoy the ride.",
    "I don't know what tomorrow holds but I know I'll figure it out. I always do. We always do.",

    # ── Miscellaneous natural conversation ─────────────────
    "Oh shoot, I think I left my keys inside. Hold on, let me check my bag. Nope. My pocket? Yes! Okay, we're good.",
    "I keep meaning to call you back and then I get distracted and then it's like midnight and I'm like, too late now.",
    "You know that thing where you walk into a room and forget why you went in there? That's been my entire day.",
    "I wrote myself a note and now I can't read my own handwriting. I think it says pick up milk? Or maybe it says something else entirely.",
    "My alarm didn't go off this morning so I woke up in a full panic. Turns out it was Saturday. I panicked for nothing.",
    "I just realized I've been humming the same song for three days straight and I don't even like the song.",
    "Do you ever have one of those days where everything is mildly inconvenient? Not bad, just annoying. That's today.",
    "I ran into someone I know but I couldn't remember their name so I just kept saying hey you. I think they noticed.",
    "I told myself I was going to go to bed early tonight and here I am. It's midnight and I'm wide awake.",
    "I need to start writing things down because my memory is absolutely not what it used to be.",
    "Can you hold this for a second? Actually no, give it back. Actually wait, yeah hold it. Sorry, I'm a mess.",
    "I just sneezed like eight times in a row and now I feel like I ran a marathon.",
    "Why do I always remember the things I need to do right as I'm falling asleep? Every single time.",
    "I waved at someone I thought I knew and it was a complete stranger. We're both pretending it didn't happen.",
    "I've been sitting here trying to think of the word and it's right on the tip of my tongue. What's it called when... oh forget it, it'll come to me later.",
]
